### ISSUE TITLE
PCH nodes are not migrated when cached

### ISSUE THREAD

**Issue by bkslasher** [fastbuild/fastbuild#530] opened 2019-01-25 11:28 UTC
When using `.AllowDBMigration_Experimental = true` ObjectLists that use PCH and caching are not migrated when DB is re-parsed. This is cased by PCHCacheKey not yet calculated in new nodes.
Here is my proposed fix: https://github.com/fastbuild/fastbuild/compare/dev...bkslasher:fix_cached_pch_migration
@ffulin Can you please check it? If it's OK I'll create a PR.

**Comment by ffulin** [comment] 2019-01-28 01:07
Thanks for the bug report! I took a look at your change and it looks like a good fix for this issue. If you convert that to a PR, i'll integrate it. I've also created a test to reproduce the problem, so I'll add that when I do the integration.

One thing to note is that there is another related bug: If the node is migrated, we still lose the PCHCacheKey, which means object using this PCH will not be able to get hits from or store to the cache until the next time the PCH is rebuilt. I have a fix in mind for this though, which I can apply after this one is integrated.

**Comment by ffulin** [comment] 2019-02-02 18:32
I've integrated your fix, and it will be in the next release (v0.98). I'll leave this issue open until that version is released.

A fix for the second issue I mentioned is also coming shortly.

**Comment by ffulin** [comment] 2019-02-02 20:55
I've fixed the bug where, post DB migration, objects using MSVC precompiled headers would not be retrievable from the cache until the PCH was rebuilt (https://github.com/fastbuild/fastbuild/commit/4fa74ef970765934ec9266e28a4286c30f16ab27). This fix will also be in the next release (v0.98)

**Comment by ffulin** [comment] 2019-05-02 05:46
v0.98 has now been released and contains a fix for the issue you reported and the additional one I discovered. Thanks for reporting the problem and your help fixing it.

**Closed by ffulin** 2019-05-02 05:46 UTC
Labels: Bug, Resolved In Next Version
