### ISSUE TITLE
Home directory paths sometimes mangled on Windows

### ISSUE THREAD

**Issue by miv-ableton** [fastbuild/fastbuild#936] opened 2022-11-09 11:02 UTC
On Windows 11 I ran this command from the working directory `C:\Users\miv\projects\live`:

```
FBuild.exe -clean -config ide\Live\win_64_dll\Debug\Live.bff
```

This produced this error:

```
Failed to set working dir. Error: 3 (0x03) Dir: 'C:\Users\Mike Verdone\Projects\live'
```

Somehow my home directory `miv` was transformed to my full name, and FBuild then tried to set this nonsense directory to the working directory.

This regression was introduced in Fastbuild 1.08. In 1.07, the command succeeds.

**Comment by ffulin** [comment] 2022-11-10 08:55
Thanks for reporting this. This is caused by the working dir canonicalization feature of v1.08.
I will think about the best way to fix this.

**Comment by ffulin** [comment] 2022-11-19 06:03
I've changed the way path canonicalization is implemented in a way that should avoid this problem: https://github.com/fastbuild/fastbuild/commit/b8378b4f9535960f78686c05eea60995c5e96139

This fix will be in the next release (v1.09). I'll keep this issue open until that version is released.

Thanks again for reporting the problem.

**Comment by miv-ableton** [comment] 2022-11-21 08:26
Thanks for the quick fix! I'll retest when 1.09 is out.

**Comment by ffulin** [comment] 2023-03-11 01:20
v1.09 has been released and includes the fix for this issue. Thanks again for reporting it!

**Closed by ffulin** 2023-03-11 01:20 UTC
Labels: Bug, Resolved In Next Version

**Comment by miv-ableton** [comment] 2023-03-13 07:03
Confirm that it fixed the issue for me. Thank you so much!
