### ISSUE TITLE
Command line too long

### ISSUE THREAD

**Issue by ruby0x1** [fastbuild/fastbuild#752] opened 2020-06-02 16:24 UTC
Note that this issue is similar to #87 but not the same.

Setup:
- on windows
- version 0.99 or 1.00
- custom emscripten target _(compiles+links perfectly on mac/linux)_
- `emcc` as compiler (emcc.bat)
- `emcc` as linker (emcc.bat)
- `emcc` as librarian (emcc.bat)
- `CompilerFamily` is set to `clang`
- `LibrarianType` is set to `ar` _(also tried `msvc`)_
- `LinkerType` doesn't have a clang option... _(I tried `msvc` and the others)_

The issue:
```js
6> Lib: C:\dev\project\build\bin\bullet2\web-emcc-dev\bullet2.bc
c:\emsdk\upstream\emscripten\emcc.bat -o ........... +16239 characters of args
6> The command line is too long.
6> Failed to build Library. Error: 1 (0x01) Target: 'C:\dev\project\build\bin\bullet2\web-emcc-dev\bullet2.bc'
FBuild: Error: BUILD FAILED: lib-bullet2-web-emcc-dev
Time: 0.048s
```

This is the librarian step of a `Library` node. 
The issue here is (seemingly) coming from this error, which would make some sense since 1. it's a bat file 2. it's way more than 8192 characters 3. fastbuild is not (and can't) autodetect the need for a response file.

https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation

Details: emscripten builds via `emcc.bat`, which simply calls `emcc.py` which does all the work. It forwards the args as is. emcc.py handles the use of response files, **but there is no way for me to tell fastbuild to use them**. It seems that the assumptions in fastbuild are quite limiting here. The assumption about the max length of a command line, as well as the assumption about which linkers can use response files. 

It seems like the one solution proposed in #87 would be perfect for these situations (`m_ForceUseResponseFile`). e.g

`LibrarianForceUseResponseFiles`
`LinkerForceUseResponseFiles`
`CompilerForceUseResponseFiles`

I personally don't feel that hardcoding more assumptions (like emcc.bat and emcc) would be ideal, since this will come up time and time again for any compiler/linker/librarian that is not hardcoded.  

Regardless this is a blocking issue, since I can't compile emscripten builds on windows with fastbuild, due to the missing use of a response file. I'd love to be able to be explicit and make that behaviour well defined, rather than the tool trying to guess :) p.s I expected forcing a LibrarianType to do something, but the behaviour was the same. 

Thanks for the great tool as always, @ffulin

**Comment by ffulin** [comment] 2020-06-03 03:52
It does sound like the proposed solution you linked (https://github.com/fastbuild/fastbuild/issues/87) is the right way to fix this issue - exposing explicit control of response files for situations where FASTBuild does not or cannot detect that it's ok to use them.

**Comment by ruby0x1** [comment] 2020-06-11 00:00
Hi @ffulin! I just noticed a new release, this commit https://github.com/fastbuild/fastbuild/commit/24bbcdc70cc6e6c6f321fa7134ce2df145e0ff0e isn't related to this issue right? I just wanna make sure I don't miss a potential fix (both to test, and to use), though that fix seems unrelated.

**Comment by ffulin** [comment] 2020-06-11 01:51
Hi! That fix allows FASTBuild to work with longer paths on Windows 10 where long path support has been enabled in the registry. It unfortunately has no impact on command line lengths supported by the OS, which are still limited to 32KiB.

**Comment by ffulin** [comment] 2020-06-21 15:57
There is an existing PR that sounds like it would solve this issue: https://github.com/fastbuild/fastbuild/pull/501

**Comment by ruby0x1** [comment] 2020-06-21 17:11
At a quick glance it seems to be similar to what I was thinking, yep! 

As long as it doesn't use the Windows as an excuse to guess, and respects the flag, it seems good to me (otherwise it'll still fail on custom tools on Windows)!

**Comment by ffulin** [comment] 2020-06-27 18:57
I've integrated the referenced change. It will be in the next release (v1.02).

I'll leave this issue open until that version is released.

**Comment by ruby0x1** [comment] 2020-06-29 03:10
Great thanks @ffulin , if there's a nightly to test ahead of the release let me know. 
Looking forward to it either way!

**Comment by liudulab** [comment] 2020-07-15 04:36
@ffulin is there another way to fix this error except waiting new release version?

**Comment by ffulin** [comment] 2020-07-17 15:30
I'm not aware of any practical work-around. The new version should be released fairly soon though.

**Comment by ruby0x1** [comment] 2020-07-30 03:51
@ffulin I finally had a chance to test this by cloning dev branch and building myself. 

**Unfortunately it doesn't work** as it needs to for this to be considered resolved.

Specifically, in `bool Args::Finalize`, we have this: `const uint32_t argLimit( 32767 );` inside a windows block.
Followed by this:

```cpp
        if ( totalLen < argLimit )
        {
            #if defined( ASSERTS_ENABLED )
                m_Finalized = true;
            #endif
            return true; // Ok to proceed
        }
```

The problem is my compiler REQUIRES response files because the command line is too long. 
It is not because of the windows 32767 limit, it's a different *unguessable* unknowable limit that fastbuild cannot control. 

So in my case: I am _allowing_ response files, but fastbuild is still overriding the decision and not using them.
As stated above in the goals, it needs to be absolute, currently it says "I can use response files, but I'm not going to because of this arbitrary check you can't control". Instead, I'd imagine "I'm using response files because you told me to".

**If I comment that block out `totalLen < argLimit`, my compiler works**, because it gets the response files.

Hope that helps, and glad I caught that before a release.
This will still be a blocker with the code as is.

**Comment by ffulin** [comment] 2020-08-26 06:27
v1.02 has now been released which includes the new options. Should this not address the issue for you, please let me know.

**Closed by ffulin** 2020-08-26 06:27 UTC
Labels: Enhancement, Resolved In Next Version

**Comment by ruby0x1** [comment] 2020-08-26 06:29
Thanks @ffulin, I've been caught up, but testing the release will be simpler and I'll let you know ASAP.

**Comment by ruby0x1** [comment] 2020-08-27 01:03
Just confirming this works great in 1.02, thanks again @ffulin !

**Comment by liudulab** [comment] 2020-09-04 07:34
@ffulin i try to set .LinkerForceResponseFile = true in Executable, and there is another issue: linker.exe don't know what to do with @..\AppData\Local\Temp\.fbuild.tmp\0xc412c495\core_3\args.rsp.

**Comment by ffulin** [comment] 2020-09-05 01:40
@liudulab - this option will only work if your linker supports response files and accepts the @filename syntax to specify them.
Which linker are you using? Does it support response files?

**Comment by liudulab** [comment] 2020-09-07 00:09
i am using cctc linker which is used to embedded MCU develop, similar to arm. if the linker not support response files, is there another way to fix "Command line too long"?

**Comment by ffulin** [comment] 2020-09-07 01:11
If the linker doesn't support response files, the only option is to make the linker command line shorter. There are potentially a few ways to do this, depending on how your setup is configured. If you can provide a (redacted if necessary) copy of your linker command line I may be able to make some suggestions. Perhaps consider raising a new issue to track this.

I tried to find some information about the linker you mentioned (cctc) as I'm not familiar with it, but I found nothing. It might be possible that it does support response files, but needs a different syntax. If you have access to the documentation or can get support from the vendor/developer you could perhaps see if this is the case.

**Comment by liudulab** [comment] 2020-09-09 00:01
@ffulin  the linker full name is TASKING VX-toolset for TriCore v6.2r2.  there are about 1500 file in my project, whether caused by files count ?

**Comment by ffulin** [comment] 2020-09-09 01:44
@liudulab I will need some more information from you. Please create a new issue so we can discuss your problem there.
