### ISSUE TITLE
fatal error C1001: An internal error (compiler file 'msc1.cpp', line 1518) with vs2017 15.8.4

### ISSUE THREAD

**Issue by TerryChan** [fastbuild/fastbuild#492] opened 2018-09-21 01:46 UTC
When I use VS2017 15.8.4 and Fastbuild 0.96 to do distributed build for Unreal Engine 4.2, I got the error below:

>  4>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.15.26726\include\comdef.h : fatal error C1001: An internal error has occurred in the compiler. 
> 4>(compiler file 'msc1.cpp', line 1518) 
> 4> To work around this problem, try simplifying or changing the program near the locations listed above. 4>Please choose the Technical Support command on the Visual C++ 
> 4> Help menu, or open the Technical Support help file for more information

I found this issue was introduced by latest Visual Studio for distributed build, becasue: 
1. I didn't get this issue in vs2017 15.7.6 wihch is an older version 
2. There is no this issue when disabled fastbuild

I found the same issue in [ visual studio community](https://developercommunity.visualstudio.com/content/problem/313306/vs2017-158-internal-compiler-error-msc1cpp-line-15-1.html), but looks like they didn't provide a solution for vs2017 15.8.4. Is there any solution for vs2017 15.8.4?

**Comment by TerryChan** [comment] 2018-09-25 10:28
With the suggestion of @dummyunit ,the issue addressed (note, just add .AllowDistribution = false cannot address this issue, you must add both .AllowDistribution = false and .AllowCaching = fasle). I modified for Module.VisualStudioSourceCodeAccess.cpp and Module.DatabaseSupport.cpp. Now I can build UE 4.2 both in VS 15.8.4 and VS 15.8.5. Thanks @dummyunit @ffulin 

By the way, @ffulin do you have more documents about FB on game development? expecially on Unreal Engine.

**Comment by ffulin** [comment] 2018-10-02 06:33
@TerryChan - I'm going to close this issue. Let me know if there is more to be done and we can re-open or create a new issue as needed.

**Closed by ffulin** 2018-10-02 06:33 UTC
Labels: Question

**Comment by RPG3D** [comment] 2018-12-27 14:43
@TerryChan ,Hi, how to disable cache & distribution on VisualStudioSourceCodeAccess module? add sometag to Action?

**Comment by nucleiis** [comment] 2019-01-14 02:04
Hi all, sorry for commenting on closed issue. We faced the same issue with VS2017 15.9.4 and FastBuild 0.97, compilation works with cache turned off but that actually slows down build time 2~2.5 times. 

Is there any way to turn on the cache feature or should I upgrade to VS2019?

**Comment by ffulin** [comment] 2019-05-23 05:35
@nucleiis - I missed your original question. I think the only work around (while keeping the cache) it to upgrade or downgrade to a compiler version that doesn't have this bug.

**Comment by Hvvang** [comment] 2022-10-09 14:48
Hi, @ffulin. Also sorry for commenting for this issue after it had closed.
I also encountered a similar problem while compiling my project in unreal engine distributedly with FASTBuild.
I'm using the latest version (1.07 fastbuild) with my unreal engine and I'm getting a compile error in the .tli file (_error C3861: 'FAILED': identifier not found_) : missing a base macro from the windows sdk.
This is strange, because with a normal build without fastbuild, the project compiles.
Maybe someone can recommend a walkaround this problem.

**Comment by ffulin** [comment] 2022-10-12 07:38
@Hvvang I'm sorry but i'm not sure why your Unreal integration isn't working. Best to ask the creator of the integration you are using about that.

**Comment by ffulin** [comment] 2022-10-13 09:13
Unfortunately i don't know what the source of your problem is. It could be:
a) a bug in the Unreal integration
b) a missing feature in FASTBuild v1.07 (the v0.99 they had was custom but no PRs were created so i'm not sure what was done)
c) a compiler bug as hinted at in this thread

It should be possible to use -showcmds to see what is being invoked and check that those args are correct. It should then be possible to take those args and directly invoke the compiler and see what the preprocessed output looks like to see if there is a compiler bug.

If the error for this particular module only occurs in certain cases (like using distribution) you could also try disabling distribution just for that one module or library as a work-around.

**Comment by Hvvang** [comment] 2022-10-13 09:31
@ffulin, is -showcmds fastbuild command? 
to me it looks like fastbuild didn't include what the builtin ue buildtool did. But I compared the commands (clang-commands.json) and the .bff file and they are virtually identical. That's why I don't know how to fully and completely make sure what the problem is.
Disabling the distributed build for the module did not help. This is the first thing I did and I will add that my problem is relevant for both 0.99 and 1.07 versions of fastbuild

**Comment by ffulin** [comment] 2022-10-15 04:08
**> is -showcmds fastbuild command?***
Yes.

**>  fastbuild didn't include what the builtin ue buildtool did.**

FASTBuild invokes the compiler with arguments specified by the ue buildtool, via whatever extension/modifications you are using to integrate FASBTBuild. If the command line arg differs then it could be because the ue buildtool is not generating the FASTBuild config properly (bff) or it could be manipulation of the args by FASTBuild (rare, but there are some cases that necessitate it).

If you have a working situation and a non-working situation, the key to resolving this problem is isolating the differences between those cases. If it's not obvious at the current level, then at a lower level you could use ProcessExplorer to see the final args being used between the two situations. You should then be able to use those args to directly invoke the compiler yourself, and narrow down the difference causing the failure.

It should be noted that some compilers alter their behavior based on environment variables, so that's another thing to look out for.
