### ISSUE TITLE
Remote workers output broken object files sometimes

### ISSUE THREAD

**Issue by rhetty** [fastbuild/fastbuild#909] opened 2022-05-19 12:31 UTC
We compile cpp files with arguments ' -ide -dist -cache -profile' and occassionally some object file produced by remote workers is broken without error. The broken one is smaller in file size which is only 800 bytes and the cache key is the same as the good one.
We ran into this issue on Mac only. It works fine on Windows.
The version of FBuild is 1.05.

**Comment by ffulin** [comment] 2022-05-21 01:10
This sounds very unusual.

Is this problem reproducible on specific object files, or do different object files fail at different times?
Do you have multiple workers in your pool in both cases?
Are there any interesting differences in network topology (wired vs wifi for example) between your mac and windows machines?
Are you building your own worker, or using a stock version? Do you have any changes?
Are you able to try v1.06 to see if the problem still occurs?

**Comment by rhetty** [comment] 2022-05-23 12:20
Unfortunately it is not reproducible. It seems that different object files fail at different times.
We have multiple workers in both cases.
The machines are all wired connected.
We made a little modification and built our own worker, but it seems no harm. Anyway, i will review the modified code again and maybe try the stock version.
It there are no other ways, we will consider v1.06.

**Comment by rhetty** [comment] 2022-05-23 13:33
The broken object file is not truncated, so it should not be network problem?

**Comment by ffulin** [comment] 2022-05-25 08:19
I think i misunderstood your original post. I assumed the worker was returning a corrupt/truncated 800 byte file.
If the returned file is a valid object, but only 800 bytes then I don't quite understand why or how that could happen.

The only idea i have is that something mac specific is causing two objects to operate in the same space for some reason, perhaps one overwriting the other for example.

What i'd suggest as next steps is to try and narrow down the problem.
There are a few things I can suggest:
a) If possible, revert your changes just to be sure they are not involved
b) Remove the use of -cache. The cache should not be relevant here, but this is an easy simplification we can make
c) Try building with only 1 worker and see if you can still replicate the problem
d) Try limitting that 1 worker to 1 core and see if you can still replicate the problem

Depending on what you find, it might give us a lead on the problem.

Finally, if you are willing to provide the 800 byte file (if it is free of sensitive info) that might also yield some interesting information.

**Comment by ffulin** [comment] 2022-05-26 07:03
Thanks for providing the object file. It seems to be valid, but simply empty, which implies something is wrong with the compiler invocation. I think our next best steps are to try to isolate the repro case as I mentioned before.

In addition to that, you can try using -forceremote to make sure every object file is sent to the remote worker if it can be done remotely. In combination with the other things I mentioned, this might make a repro case easier to find.

**Comment by rhetty** [comment] 2022-07-01 03:30
Hi ffulin, I found another issue:  UI mode FBuildWorker on Mac continue to consume memory (View from Activity Monitor). After running for a long time, it almostly ran out of all memory (60GB+). Then I tried to launch FBuildWorker with '-console' and its memory usage looks normal now.
I am not sure if it is related to this issue.

**Comment by ffulin** [comment] 2022-07-02 02:32
Have you been able to try using -forceremote to see if the problem is confined to specific files as opposed to random?

60GiB of memory usage is certainly not normal, and seems to imply there is a memory leak, probably specific to the OSX worker. Do these failures correlate with that high memory usage? For example if you see a worker in this state, and you explicitly set the worker list on another machine using .Workers in the Settings() of the bff and build with -forceremote, does it allow you to reproduce the problem?

**Comment by rhetty** [comment] 2022-07-04 02:25
Yes, i am using -forceremote but the emtpy object file has not showed up yet.
When a worker is in high memory usage, FBuild on other machines can not connect to it and keeps outputing connection failed.

**Comment by ffulin** [comment] 2022-07-14 08:48
It turns out that I recently fixed a bug that is the cause of this issue, but I didn't connect the two despite it being completely obvious in retrospect: https://github.com/fastbuild/fastbuild/commit/9181f5c0fcb0f5d52fa9f57b43ec85989ce461c2

That fix will be in the next release (v1.07). I'll keep this issue open until that version is released.

Side note: Another user reported this issue but for them it was manifesting as a compiler error - clang was complaining that it was being passed an empty object file. It might be that your build config is missing some warnings or doesn't have "warnings as errors" enabled. Might be worth checking.

**Comment by rhetty** [comment] 2022-08-04 10:50
Is there a problem if I merge this fix to v1.05?

**Comment by ffulin** [comment] 2022-08-13 09:48
It should be safe to integrate this fix back to v1.05
However, v1.06 and v1.07 (just released) contain several important bug fixes for distributed compilation so I strongly suggest updating to the latest version.

As v1.07 has now been release I will close this issue.

**Closed by ffulin** 2022-08-13 09:48 UTC
Labels: Bug, Resolved In Next Version
