### ISSUE TITLE
Dependencies not being properly evaluated

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#215] opened 2017-03-15 02:08 UTC
I ran into an issue where I was working on a cpp file (lets call it Module.cpp) in a project (call it PluginProject), and meaningfully modifying an external header (call it GlobalMacros.h) which was included indrectly (via e.g. Globals.h) by the precompiled header of PluginProject did not cause a rebuild of module.cpp.

The directory structure looks like this (totally fake names and such):
dev/
  PluginProject/
    PrecompiledHeader.h
    Module.cpp
    ...
  PluginProjectB/
    DifferentPrecompiledHeader.h
    DifferentModule.cpp
  PluginProjectC/
  PluginProjectN/
  ,,,
  GlobalFiles/
    Global.h
    GlobalMacros.h
  
I'd expect FastBuild to get dependency information from the compiler to supplement its own dependency tree for cases like this where an #include is not a part of the current project.

I haven't tested to see which configurations this is broken in (e.g. msvc vs. clang vs. emscripten, etc.) - but I can do more fact finding if that would be helpful.

**Comment by ffulin** [comment] 2017-03-17 03:33
The case you mention (including a header indirectly via another header via the precompiled header) is a pretty normal use-case and as far as I know works for all supported compilers.

FASTBuild extracts these dependencies by invoking the compiler with various command line options and parsing the output. If any dependency information is missing, that would indicate that:
a) The compiler is not supported (so FASTBuild doesn't know what args to use)
b) There is a bug (as we know there currently is with clang.exe being invoked when called cl.exe: https://github.com/fastbuild/fastbuild/issues/206)

The case you mention (including a header indirectly via another header via the precompiled header) is a pretty normal use-case and as far as I know works for all supported compilers.

If you can narrow down which cases are not working for you, we should be able to quickly determine if it's a case of a) or b).

**Comment by missmah** [comment] 2017-03-18 17:52
I'll try to take a look at this again soon and see what I can glean about the situation with Emscripten (and see whether it appears in any other Clang related builds of ours)

Thanks!

**Comment by Stof25** [comment] 2017-05-04 08:58
I have the same problem with clang compilations using the 0.92 version. As far as I know, it's caused by FastBuild not detecting correctly we are using the clang compiler and forgetting to add the -frewrite-includes option.

I think it's because I specify explicitly which clang version I use ( /usr/bin/clang-3.9 for example ). If I go through a symlink instead called clang that points to the exact same file, then FastBuild will add the -frewrite-includes when it does the preprocess stage.

In fact, it doesn't seem like fastbuild does the preprocess phase at all.

**Comment by ffulin** [comment] 2017-12-02 20:56
I'm going to close this issue as it is fairly old. Feel free to re-open if you want to continue investigation.

**Closed by ffulin** 2017-12-02 20:56 UTC
Labels: Need More Info (or Blocked), Question
