### ISSUE TITLE
Question about 'ObjectList() '

### ISSUE THREAD

**Issue by cfers** [fastbuild/fastbuild#898] opened 2022-03-21 06:23 UTC
ObjectList( alias )         ; Alias
{
  ; options for compilation
  .Compiler                 ; Compiler to use
  .CompilerOptions          ; Options for compiler
  .CompilerOutputPath       ; Path to store intermediate objects
}

The ObjectList()  configure  '.CompilerOutputPath' will lead to the all *.obj files are put to the same dir. if I have two `has-the-same-name` source files, and their content and path are different, that will  cause compile conflicting, as the picture shows.  
![image](https://user-images.githubusercontent.com/16715935/159213615-7655fffe-8ed2-48a9-9ea7-345e7ccbf32f.png)

**Comment by ffulin** [comment] 2022-04-01 23:35
FASTBuild uses the relative path of cpp files to generate the paths to objects to allow files with the same name to exist in the same library. This can be foiled in one of two ways:
a) Performing two directory listings such that both files exist at the root of those directories
b) Listing files individually

You haven't specified, but I'm guessing from the above that you are using some sort of bff generator (probably an Unreal integration)? If so, it seems likely that the problem is b)

If that's the case, this can be solved by updating your generator to provide a base path for the manually listed files using this option:
```.CompilerInputFilesRoot      ; (optional) Root path to use for .obj path generation for explicitly listed files```

Let me know if that helps, or if there is a more complex problem here I'm missing.

**Comment by cfers** [comment] 2022-04-03 01:46
Thanks a lot~ I am writing a msvc IDE plugin(for c++ vcproj bff generating) . At present,  I solved the problem by modifying 
 the .CompilerOutputPath to different directory:
- `a/main.cpp :  .CompilerOutputPath = a/ `
- ` a/b/main.cpp : .CompilerOutputPath = a/b/`
 
- [ ]  I will verify your method, and give the feedback:
`.CompilerInputFilesRoot ; (optional) Root path to use for .obj path generation for explicitly listed files`

**Comment by ffulin** [comment] 2022-04-03 02:02
This project might be of interest to you: https://github.com/liamkf/msfastbuild

**Comment by cfers** [comment] 2022-04-03 11:12
Oh, my project is exactly based on [https://github.com/liamkf/msfastbuild](https://github.com/liamkf/msfastbuild), there's a lot of room for improvement in it . for example, custom build & prebuild/postbuild event  are not supported, projects dependencies  are not properly handled,  besides, I can not build  multi-projects at the same time,  can not abort the compiler process... ,  But, I have solved Most of them ;)

**Comment by ffulin** [comment] 2022-08-13 09:55
I think this question has been answered so I'm going to close this issue. Let me know if you need any followup and we can take appropriate action if needed.

**Closed by ffulin** 2022-08-13 09:55 UTC
Labels: Question
