### ISSUE TITLE
Usage of -nounity generates isolated files afterwards

### ISSUE THREAD

**Issue by aganea** [fastbuild/fastbuild#838] opened 2021-06-02 13:45 UTC
We've noticed that using -nounity of a given target would affect the FDB in some ways that, a subsequent compilation of the same target but without -nounity, would create a lot of isolated files. The problem occurs on the build system as well, where there are no files checked out from P4. The issue usually happens after a Nightly build, which compiled NoBlob but by using -nounity, and then a regular Daily build occuring on the same machine, but without -nounity. We are using FASTBuild 1.04.

**Comment by ffulin** [comment] 2021-06-02 15:34
There are some quirks around nounity as described here: https://fastbuild.org/docs/options.html#nounity (it is marked as experimental for this reason). What you've described may be another quirk.

The way dependencies are managed has changed since -nounity was implemented, so it's possible this behavior can now be improved/resolved (and the feature made non-experimental). I'd need a bit of time to dig into that.

In the short-term, one potential work-around is to delete the .fdb file when switching to/from -nounity. That will cause more building to occur than might otherwise be necessary, but perhaps for a nightly check this would be ok.

**Comment by aganea** [comment] 2021-06-02 18:20
Yeah that's we ended up doing. But -nounity is interesting since it doesn't require to have an additional "NoUnity" target like we were doing before. Plus, I'd like ideally to have a feature where whenever we isolate a file, its corresponding unity is recompiled as isolated files as well, to improve the build times (to prevent 3-4 min spikes waiting for the updated unity to compile). Once the isolated file is submitted, everything should back into a unity. So my whole point is that there's value in investing into -nounity :)

**Comment by ffulin** [comment] 2021-06-03 05:12
**> So my whole point is that there's value in investing into -nounity :)**

Certainly the plan is to iron out any problems in the implementation and promote -nounity to a 100% supported feature. I mentioned the current known problems, though I'm not sure if they explain the behavior you are seeing. I think this will require some investigation to fully understand.

**> I'd like ideally to have a feature where whenever we isolate a file, its corresponding unity is recompiled as isolated files as well,**

Do you mean a mode where as soon as one file is isolated, all files are isolated?

**Comment by aganea** [comment] 2021-06-03 12:08
> Do you mean a mode where as soon as one file is isolated, all files (in that specific UnityXX.cpp) are isolated?
Yes.

**Comment by aganea** [comment] 2021-06-03 12:18
TBH, I'd like to go back to regular, "no unity" compilation at some point. Right now we can't, one issue being the local preprocessing bottleneck-- but we could with local dependency scanning and "always remote" compilation + virtualization of the filesystem on the remote worker (to have deterministic builds). "No unity" targets would also require in-process compilation (per client connected to an fbuildworker), to work around NT kernel locks when launching multiple exes really quickly; and also to share state between TUs (just caching file accesses between TUs is already a huge benefit, especially on many-core machines). Still a long way to go, but I'm confident :)

**Comment by ffulin** [comment] 2021-06-03 14:45
**> I'd like to go back to regular, "no unity" compilation at some point.**

It would be ideal if Unity wasn't necessary, but I don't see that being the case any time soon.

Even if the parsing redundancy problems and process invocation overhead were somehow fixed, apart from the compile-time speedups, Unity brings other benefits:

**Link time improvement**
Unity compilation greatly reduces the total size of object files and the number of symbols input into the linker. In some extreme examples, I've seen link times reduced by 10x through the use of Unity. In one extreme example, I saw:
* No Unity: 40mins clean build including 8 minutes of linking
* Unity: 4 mins clean build including sub 30s linking
This literally made clean builds twice as fast as linking only!

**Code generation improvement**
I've seen improvements to inlining and knock-ons to other optimizations through the use of Unity. In a way, it partly does the job of link-time code generation, but at compile time. This can result in modest, but measurable real-world runtime performance improvements. Static analysis can similarly benefit from the larger function implementation visibility.

**Disk space reduction**
Unity can reduce disk space for object files can be reduced by as much as an order of magnitude. Probably the least important benefit, but still one that can be important when there are many configs. It can be particularly important on build infrastructure.

----

fwiw, in projects I'm responsible for, we don't maintain a no-unity target. We use Unity all the time (local devs and build machines in all targets on all platforms). The isolation on edit takes care of *most* include maintenance. We balance the size of unity files to keep the first edit that splits a unity file reasonably performant, sacrificing some clean build time to do so.

**Comment by aganea** [comment] 2021-06-03 15:06
Thanks for getting back so quickly :) I agree with your points, ATM **it is** beneficial to use unities. I am just thinking more on the long term: blobbing TUs is the compiler's responsability not the build sytem's one.

`link.exe` still seems to suffer from slower link times in NoUnity build, however with LLD the difference is quite minimal (30 sec with NoUnity and 16 sec with Unity, built with Clang 12 and `-gcodeview-ghash` linked with LLD 12 and `/DEBUG:GHASH`)

As for code generation, I'd like to enable ThinLTO enabled by default, once the distributed linking works (this is currently being worked on). I would expect perf. with NoUnity+ThinLTO to be similar to Unity+ThinLTO. NoUnity alone would be evidently slower than Unity targets.

Disk space is a problem. Already as it stands, the ratio is 10:1 in our projects in Unity targets. For 10 bytes produced by the compiler, only 1 byte is retained/merged in the final output (PDB and EXE). This is quite wasteful, spending cycles in the compiler only to drop the data later. I find Sony's ideas a good avenue, but advances are slow, so again it's more long term: https://www.snsystems.com/technology/tech-blog/compile-faster-with-the-program-repository-and-ccache

Ideally, the compilation & link would always occur in a single process, and would talk to each other, a bit like (Thin)LTO does. I am also wondering what would happen in a few years, once we start seeing 1,000-core machines? Clearly unities would become a problem there.

Along those lines, one argument against unities is the fact machines get more and more cores, and unities by nature, tend to use them less. So we end up with spikes:

![compil_refgame_toolmode_clang_blob_48-core](https://user-images.githubusercontent.com/37383324/120666653-c10eb780-c45a-11eb-9aee-24b5ced8f27c.PNG)

You need to resort to smaller unities and find a good midpoint between your end-user PCs and the build system PCs. How do you actually balance the size of your unities on your project?

**Comment by aganea** [comment] 2021-06-03 15:12
BTW, if you're using Clang 12+ you should try `-fuse-ctor-homing`, it dramatically reduces the .OBJ sizes. Here using our largest C++ target:

![image](https://user-images.githubusercontent.com/37383324/120668367-68401e80-c45c-11eb-8fe2-8b98ca33ef37.png)

**Comment by ffulin** [comment] 2021-06-05 17:02
Thanks for the detailed info - very interesting and a lot of things we could talk about :)

**>if you're using Clang 12+**

We're not using Clang to target Windows (our primary development platform). We recently upgraded to the latest Visual Studio (~v16.8) and this halved our link times. This meant full links are now sub 10 seconds so we abandoned things like incremental linking as well (which had it's own set of problems).  For now, linking is a solved problem for us - the VS toolchain devs did a great job over the last few releases on this front.

For some of our other Target platforms we do use Clang, but we're not at the bleeding edge. I was considering an upgrade soon though, and I wasn't aware of this option, so the info about -fuse-ctor-homing is very interesting. Thanks!

**> How do you actually balance the size of your unities on your project?**

I try to keep individual unity objects so that their compile times take sub 30 seconds or so. That seems to strike a good balance between first time edit/isolation, full build time and overall parallelization. Most of our libraries don't use precompiled headers (unity usually does a better job and makes it redundant - similar to your timings), but in one of very large libraries, using precompiled headers in addition to Unity was needed to get the best balance, particularly for the rapid iteration case.

**420 MB EXE**

I'm sure you already looked into this, but that seems pretty huge! Code size as it relates to compile and link time as well as runtime memory footprint is something I look into from time to time.

**-nounity**

I couldn't reproduce the exact problem you mentioned, but when I went to use -nounity I found it not working all in the most basic of cases (clean normal build, and then immediately -nounity with no other changes was not working). I dug into it and it was broken by recent changes to dependency management.

I went ahead and fixed the bugs as well as improving some existing behavior. (https://github.com/fastbuild/fastbuild/commit/9cb901b740996b842775fae48fc1a014893dbb01). I also added test coverage.

With these changes, I now find that adding/removing -nounity works reliably. This restores the functionality of before, but also fixes a long-standing TODO related to -nounity which was to eliminate some unnecessary recompilation when switching back and forth. It now does the strictly minimal amount of building (i.e. it's fully incremental like everything else)

The feature is still marked as "experimental" in the documentation for now, just in case we uncover some more issues, but to the best of my knowledge the feature is now 100% complete.

**Comment by ffulin** [comment] 2021-06-05 17:03
The -nounity fixes will be in the next release (v1.06). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment] 2022-04-15 07:47
v1.06 has now been released. This issue touched on a bunch of items, but the core -unity feature has been overhauled to make it reliable.

**Comment by ffulin** [comment] 2023-01-29 00:15
I missed closing this issue back when v1.06 was released. Switching back and forth should work as expected but we can raise issues for any remaining or new problems.

**Closed by ffulin** 2023-01-29 00:15 UTC
Labels: Bug
