### ISSUE TITLE
pragma push_macro error on visual studio 2015

### ISSUE THREAD

**Issue by myevan** [fastbuild/fastbuild#256] opened 2017-06-07 11:55 UTC
I met syntax error when building unreal engine (4.16) with fastbuild on visual studio 2015
but it's ok without fastbuild.

```
PUSH_MACRO(check) // error: C2059: syntax error: ')'
```

the macro is implemented as follows:

```
#define PUSH_MACRO(name)    __pragma(push_macro(#name))
```

I found the problem from ObjectNode::DoBuildWithPreprocessor(...) and cl.exe with option /E makes unexpected result T_T) 

I make a example that you can check the bug on  https://github.com/myevan/fastbuild_examples/tree/master/vc2015_pragma_push_macro
```
C:\Projects> git clone https://github.com/myevan/fastbuild_examples
C:\Projects> cd fastbuild_examples\vc2015_pragma_push_macro
C:\Projects\fastbuild_examples\vc2015_pragma_push_macro> fbuild -clean
2> Obj: C:\Projects\fastbuild_examples\vc2015_pragma_push_macro\Out\main.obj
2> PROBLEM: C:\Projects\fastbuild_examples\vc2015_pragma_push_macro\Out\main.obj
main.cpp
C:\Projects\fastbuild_examples\vc2015_pragma_push_macro\main.cpp(4): error C2059: syntax error: ')'
C:\Projects\fastbuild_examples\vc2015_pragma_push_macro\main.cpp(5): error C2059: syntax error: ')'
2> Failed to build Object (error 0x2) 'C:\Projects\fastbuild_examples\vc2015_pragma_push_macro\Out\main.obj'
FBuild: Error: BUILD FAILED: all
Time: 0.067s

C:\Projects\fastbuild_examples\vc2015_pragma_push_macro>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" /c /E main.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
#line 1 "main.cpp"



)
)

int main()
{
        return 0;
}

```

**Comment by yass007** [comment] 2017-06-07 14:23
Hi @myevan,

Thanks for reporting the issue. I was just about to write about it :)

Did you by any chance try to see if the issue exists in 2017?

As a temporary workaround I found that this works:

`#pragma push_macro("check")

[... Insert code...]

#pragma pop_macro("check")
`

**Comment by myevan** [comment] 2017-06-08 03:18
I tested the code on in 2017 and got same results T_T)

```
C:\Projects\fastbuild_examples\vc2017_pragma_push_macro>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\cl.exe" /c /E main.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25019 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

main.cpp
#line 1 "main.cpp"



)
)

int main()
{
        return 0;
}
```

It works well that you said. But the macro is for cross platform and I should use it if possible. orz;;

This is the code in CoreMiscDefines.h (UnrealEngine-4.16.0)
```
// Turns an preprocessor token into a real string (see UBT_COMPILED_PLATFORM)
#define PREPROCESSOR_TO_STRING(x) PREPROCESSOR_TO_STRING_INNER(x)
#define PREPROCESSOR_TO_STRING_INNER(x) #

// Push and pop macro definitions
#ifdef __clang__
	#define PUSH_MACRO(name) _Pragma(PREPROCESSOR_TO_STRING(push_macro(PREPROCESSOR_TO_STRING(name))))
	#define POP_MACRO(name) _Pragma(PREPROCESSOR_TO_STRING(pop_macro(PREPROCESSOR_TO_STRING(name))))
#else
	#define PUSH_MACRO(name) __pragma(push_macro(PREPROCESSOR_TO_STRING(name)))
	#define POP_MACRO(name) __pragma(pop_macro(PREPROCESSOR_TO_STRING(name)))
#endif
```

**Comment by ffulin** [comment] 2017-06-08 04:59
I've reproduced the bug in VS2013. With other bugs in the preprocessor I've sometimes been able to work around them by modifying the macro (inserting spaces for example), but I couldn't find any way to make that work.

We might need to report this bug to MS via their connect website.

**Comment by myevan** [comment] 2017-06-09 02:05
Thanks for checking the bug : ) 

I reported it by using visual studio feedback and hope their answer

**Comment by molixiaoge** [comment] 2017-06-27 06:32
I have the same problem with unreal 4.16 + visual studio 2015 sp3 +fastbuild 0.93 x64

**Comment by deadwizad** [comment] 2017-08-13 19:36
Issue still persists in 4.17 - VS 2017 - FB 0.93 x64.

**Comment by myevan** [comment] 2017-08-17 00:36
I finally got feedback from MS! >ㅇ<)!!

> This bug will be fixed for VS2017 15.5 release.

**Comment by molixiaoge** [comment] 2017-08-17 01:20
That's not good news

**Comment by deadwizad** [comment] 2017-08-17 17:06
Did we get an eta on when thats going to drop?

**Comment by BrodyHiggerson** [comment] 2017-08-18 01:54
@myevan do you have a link to the report you made? Just curious.

**Comment by ffulin** [comment] 2017-08-18 02:20
@deadwizad 15.3 just landed, and supposedly the release cadence is every 6 weeks (https://www.visualstudio.com/en-us/productinfo/vs2017-release-rhythm). So I guess 3 months?

**Comment by myevan** [comment] 2017-08-18 13:23
@BrodyHiggerson You can search my report to type "pragma" on Microsoft Visual Studio - Report & Problem (Main Menu: Help > Send Feekback > Report a problem). I don't know the public web link of my report and received the answer from ms by email : )

**Comment by ClxS** [comment] 2017-08-22 22:13
For those who're having this issue with UE 4.16, here's a quick workaround:
File: Engine\Source\Runtime\ClothingSystemRuntime\Public\NvClothIncludes.h
Change: `PUSH_MACRO(check)`
to: `#pragma push_macro("check")`

In my version, it's the only file they've used the PUSH_MACRO macro rather than the pragma directly. There might be a few more in 4.17 but the same workaround will probably work.

**Comment by ffulin** [comment] 2017-08-25 19:54
@hillin - I got a notification that you added details of a work-around, but it seems to be missing from this issue. Did you remove it on purpose? (Was the work-around no good?)

**Comment by hillin** [comment] 2017-08-26 04:59
@ffulin I'm not sure, what does the notification look like? I adopted the #pragma workaround and it worked well.

**Comment by BrodyHiggerson** [comment] 2017-08-26 05:19
@ffulin @hillin I believe it was a user by the name "Carl" that posted and then deleted. Their work-around was what was mentioned earlier, and it works;

> For those who're having this issue with UE 4.16, here's a quick workaround:
> File: Engine\Source\Runtime\ClothingSystemRuntime\Public\NvClothIncludes.h
> Change: PUSH_MACRO(check)
> to: #pragma push_macro("check")
> 
> In my version, it's the only file they've used the PUSH_MACRO macro rather than the pragma directly. There might be a few more in 4.17 but the same workaround will probably work.

**Comment by ffulin** [comment] 2017-08-29 04:04
@BrodyHiggerson - ah, thanks :)

**Comment by ffulin** [comment] 2017-12-30 18:38
VS2015.5 seems to have been released. Has anyone confirmed if the bug is fixed?

**Comment by jackknobel** [comment] 2018-01-03 09:35
@ffulin Appears to have fixed the issue. Just tested it with the latest VS (15.5.2) and latest FastBuild.

**Comment by ffulin** [comment] 2018-01-05 04:25
@jackknobel Thanks for the confirm. I'm going to close this issue as resolved in that case.

**Closed** 2018-01-11 05:35 UTC
Labels: Question
