### ISSUE TITLE
CopyDir doesn't cope with deleted files.

### ISSUE THREAD

**Issue by kwayle** [fastbuild/fastbuild#249] opened 2017-06-02 15:44 UTC
If a file in the SourcePath directory is deleted after the build has been run once (so a .fdb file has been generated) then any further attempts to run the build will result in an error
> Copy Failed (error 2) <deleted file>
Repo is simple
`CopyDir( 'BrokenCopy' )
{
    .SourcePaths                        = 'in'
    .SourcePathsPattern                 = {'*'}
    .SourcePathsRecurse                 = true
    .Dest                               = 'out'
}`
Make two files in the in directory, run BrokenCopy once, then delete one and run it again.

I Debugged it a little, it seems that the dynamic dependencies are saved into the .fdb which is a full list of every file it found to copy so when it loads this the second time the dependencies already include a list of all the files it copied last time. DoDynamicDependencies then just appends (generally the same files) onto that list so you end up with two (or more depending how many times build has been called) copies of most files and one copy of the deleted files in the dependencies list which obviously then can't be found.

(Tested in 0.93)

**Comment by ffulin** [comment] 2017-06-04 18:32
I think you're right about the cause of the problem. This seems to be a regression in v0.93 caused by some serialization refactoring. I think this fix might be as simple as clearing m_DynamicDependencies in DoDynamicDependencies before re-building it. That would fix the ever-expanding array which of course is also bad (slowly degrading performance).  I think we it'd be good to add a test for this case to verify the fix and prevent future regressions. (We could also check your repro case against v0.92 to make sure this is a new problem)

**Comment by ffulin** [comment] 2017-06-17 18:49
I've integrated your fix (https://github.com/fastbuild/fastbuild/commit/786556e902a92bb09da3ddf16cff6151a4eb9d4a) into the Perforce mainline. The fix will be in the next release (v0.94). I'll leave this issue open until that version is released. Thanks again!

**Comment by ffulin** [comment] 2017-09-29 04:59
v0.94 has now been released and includes the fix for this issue.

**Closed by ffulin** 2017-09-29 04:59 UTC
Labels: Bug, In Next Version
