### ISSUE TITLE
Fastbuild never does incremental linking in MSVC

### ISSUE THREAD

**Issue by fran6co** [fastbuild/fastbuild#707] opened 2020-02-28 11:04 UTC
Because of this workaround => https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildCore/Graph/LinkerNode.cpp#L387

Fastbuild always deletes `.ilk` and `.pdb` files making the incremental linking always do a full linking. The problem comes from here => https://github.com/fastbuild/fastbuild/blob/dev/Code/Tools/FBuild/FBuildCore/Graph/NodeGraph.cpp#L1155

setting the timestamp to 0 before doing the build. This problem was introduced by https://github.com/fastbuild/fastbuild/commit/735ba92dfa2d37f0d53dce285a120af091903808

**Comment by ffulin** [comment] 2020-02-29 23:06
I've integrated your fix (thanks!) and added regression tests.

Normally I would leave issues open until the next version containing a fix is released, but since this bug only existed in the "dev" branch, I'll close this issue right away.

**Closed by ffulin** 2020-02-29 23:06 UTC
Labels: Bug
