### ISSUE TITLE
_Pragma("clang system_header") not working on v. 0.91

### ISSUE THREAD

**Issue by ChrisRedacted** [fastbuild/fastbuild#143] opened 2016-09-12 22:31 UTC
So I was in the process of upgrading from 0.90 to 0.91, and I unexpectedly got a failure on a clang-built version of our project.

The offending code was something like the following:
# define DISABLE_COMPILE_WARNINGS() _Pragma("clang system_header")

DISABLE_COMPILE_WARNINGS();

The error output I'm getting looks like something like this:

4>D:\project\my_file.h(23,1): error : #pragma system_header ignored in main file [-Werror]
4>  DISABLE_COMPILE_WARNINGS();
4>  ^
4>  D:\project\my_file.h(22,37): note: expanded from macro 'DISABLE_COMPILE_WARNINGS'
4>  #define DISABLE_COMPILE_WARNINGS() _Pragma("clang system_header")
4>                                                                    ^
4>  D:\project<scratch space>(12,8): note: expanded from here
4>   clang system_header
4>            ^
4>  1 error generated.

If I switch it to:
# pragma clang system_header

Everything is good. 

If I go back to 0.90, everything is once again good.

I don't see anything in the release notes that sounds like something that would have broken this behavior, and it seems strange that FASTBuild could even cause such an error to occur. Any ideas?

**Comment by ffulin** [comment] 2016-09-16 08:31
I'm going to guess that this change is related to:

> Use Clang's -frewrite-includes option to avoid preprocessing inconsistencies (Thanks to Jean-Sebastien Pelletier)

I probably should have called this out more explicitly in the "Notes" section of the changelog.

This change enabled a switch for Clang which means that rather than proprocessing all the code in the first pass, it simply flattens all the files.  For context, the benefit of this is more consistent compilation when using FASTBuild vs other systems, specifically things like:
a) Warning supression - Clang supresses warnings when generated from macro expansion in some cases where the identical expanded code (if written by hand) would generate a warning.
b) Caret positions in errors - Rather than showing the position of an error from a macro as being the expanded position, it's shown as the original position in the macro.

Now having said all this, I'm not sure why you get the error you are seeing.

**Comment by ffulin** [comment] 2016-09-17 03:40
If you want to try disabling it, to confirm it's the cause, the newly added code in v0.91 is:
```C++
            if ( isClang )
            {
                fullArgs += " -frewrite-includes";
            }
```

**Comment by krolli** [comment] 2016-12-07 21:38
Hello,

I believe I've run into same issue. Following example code compiled using clang without any issues on 0.90 but broke with 0.91:
`#define mel_HandleVkResult(value) case value : codeName = #value; break`
`mel_HandleVkResult(VK_SUCCESS);`
`mel_HandleVkResult(VK_NOT_READY);`
`mel_HandleVkResult(VK_TIMEOUT);`
`/* and so on for other errors */`
`#undef mel_HandleVkResult`

`src\vulkan\main.cpp(39,17): error: macro is not used [-Werror,-Wunused-macros]`
`#define mel_HandleVkResult(value) case value : codeName = #value; break`

I tried removing the "-frewrite-includes" and it fixed the problem. I will be honest, primary reason why I like fastbuild is that it does very little behind my back in terms of command line arguments ... at least I thought it did. I only expect it to add some switches for obtaining list of dependencies (and even those I would like to describe in Compiler() function call). I'm really confused why an option like -frewrite-includes, that can easily be added by those who want it and has no relation to build system as far as I can tell, would be forced everywhere with no way of turning it off.

In fact, looking at other things ObjectNode::BuildArgs() does, I find it rather silly. Are there any plans to make these things customizable (eg. using Compiler() call) instead of having them hardcoded? Or at least documented?

**Comment by ffulin** [comment] 2016-12-08 06:44
FASTBuild tries to modify the command line as little as possible - the less magic behaviour the better. Adding or removing options from the command line is generally only done when it's necessary to have things work properly.

This particular change was a bit of a special case, since it's not strictly needed to make things work, but resulted in far better behavior in all the cases I saw.  Specifically, this option is to address an issue where when using Clang's preprocessor, some behaviour is different. Specifically:
 - some warnings are suppressed by macros, and not suppressed when expanded by the preprocessor
 - the caret indicator in error messages did not line up properly in the output

In all the cases i tested, adding the -frewrite-includes option fixed those problems without introducing any new issues, so it seemed like a good change. The idea being that the behaviour of FASTBuild would match whatever build system someone was using before.

Given that the option seems to have some problem cases though, it seems that either:
a) it should be off by default with an option to turn it on
b) it should be on by default with an option to turn if off

In either case, i think adding this option in the Compiler() settings would be the way to go.

> What exactly is the reason for fastbuild to do multiple passes when I can only specify flags as if there was just one? 

The reason for this is that this is the mechanism by which FASTBuild supports distributed compilation and caching is to flatten everything using the preprocessor.  For consistency of behaviour, having it do this two pass compilation always means eliminating potential differences between -dist , -cache and local compilation.

**Comment by ffulin** [comment] 2016-12-08 06:47
Note that it's still not clear exactly why use of this option causes the problems reported in this issue.

**Comment by krolli** [comment] 2016-12-08 06:49
Could it have something to do with -Weverything enabled? I wouldn't be surprised the warning just wasn't enabled in your tests. I plan to have a better look at preprocessed file from clang later to see what it looks like. It might leave the macro definition in the preprocessed file, but perform macro expansion on all its uses, resulting in code where macro is unused.

**Comment by krolli** [comment] 2016-12-08 20:25
So I did a little bit of testing and I think this is really just a bug in clang. It seems to notice macro definition, but since it doesn't do macro expansion when -frewrite-includes is specified, it thinks the macro was never used and emits warning.
Also, I couldn't really find any documentation on the option. I have only ever seen it used for sending bug reports to compiler people (to make bug report with only single file instead of tons of includes) so I wonder if it's even meant to be used in everyday compilation. All it took for me to trigger the warning was pass in -Weverything.

**Comment by ffulin** [comment] 2016-12-09 02:17
Thanks for digging further. I agree with your analysis, both about this seeming like a bug, and about the option potentially being an internal option.  I think exposing use of this option as we've talked about would at least allow FASTBuild to work around the problem (I've marked the issue with the Enhancement tag to reflect that). This should be easy to add. In your example you could potentially disable the problematic warning about unused macros as well (assuming that's not critical to you).

I actually think that at least part of the reason I'm even using this option in the first place is also a bug: i.e. identical code generating different warnings if it comes from a macro is not good behaviour in my opinion. The other reason (expanded macros messing up caret positions) seems like it's unavoidable though.

**Comment by krolli** [comment] 2016-12-09 05:50
I will try filing a bugreport to clang people and see what they have to say about it, but I want to test it on their newest branch first. I've tried 3.8.1 and 3.9.0 versions and both of them emit the warning, so I suspect it is still present, but I want to make sure. Also, it seems registering to their bugzilla is a bit of a pain, so it might take a few days.

**Comment by ffulin** [comment] 2016-12-11 00:46
> I will try filing a bugreport ....

Cool. Let me know if there's anything I can do to help it along.

**Comment by ffulin** [comment] 2017-01-14 23:25
I've added an option to allow -frewrite-includes to be disabled, which will allow some more flexibility in avoiding this problem until the issue is hopefully fixed in Clang. This change (https://github.com/fastbuild/fastbuild/commit/73b89966e676b86e49ea659dc6615c62e31cc624) will be in the next release (v0.93).

**Comment by krolli** [comment] 2017-01-29 07:15
Thanks for that, I will try it when I get a chance. I've written several emails asking for access to bugzilla to report the bug, but I never got any reply so I have no idea when this will get fixed, if at all.

**Comment by krolli** [comment] 2017-02-01 07:24
So I finally got access to the bugzilla (may have had it for a while but didn't know about it due to email notification arriving) and I found out the bug has already been reported a while ago. I bumped up the report. I suspect this is a low priority thing for them though.

Here is the bug report: https://llvm.org/bugs/show_bug.cgi?id=15614

**Comment by ffulin** [comment] 2017-03-14 04:52
v0.93 has now been release which includes the work around for this problem. I think I'll leave this issue open while we try to track the clang bug.

**Comment by krolli** [comment] 2017-03-25 06:44
Thanks, tested it and it worked like a charm.

**Comment by ffulin** [comment] 2019-10-26 22:33
The bug in clang has been marked as resovled with this commit: https://reviews.llvm.org/D65371

**Closed by ffulin** 2019-10-26 22:33 UTC
Labels: Enhancement, Fixed, Question
