### ISSUE TITLE
Is it possible to reduce memory usage?

### ISSUE THREAD

**Issue by Shaggy84675** [fastbuild/fastbuild#942] opened 2022-12-17 21:08 UTC
Hello, I'm trying to use FB with UE 5.1. It seems it works and I setup it correctly (probably), but when I want to build the project, it consume all my computer memory and it became unusable after couple of minutes and I need to hard reset the whole machine. It also happens on the other machines.

Is it possible to set some maximum memory what can be used by cl.exe? I've noticed there is a /Zm option for the cl.exe and I tried to set it into Compiler() { .Environment = '/Zm100' } or Settings.Environment = { "CL=/Zm100", }, but it doesn't seems it'd work. Maybe I use it incorrectly?

What also happens is the C: drive is being used 100%. Is that normal?
![obrazek](https://user-images.githubusercontent.com/1374803/208264065-68be6ec5-a8ee-4011-ab57-896ea9a44d49.png)

Thank you for the help! If there's anything more I could provide, let me know.

**Comment by ffulin** [comment] 2022-12-18 03:33
FASTBuild by default limits its memory usage used for distributed compilation to ~2GiB, so assuming this hasn't been changed in your bff file, the bulk of the memory usage will most certainly come from the compilers. You can confirm this in task manager if you haven't already.

It's not uncommon for individual instance of the compiler to consume hundreds of MiB or even GiB in large codebases and particularly those that use Unity files (as Unreal does). I find a good rule of thumb is that for each CPU core, a machine should have ~2GiB of physical memory, though it varies between codebases and target platforms and compilers. With some versions of Clang, I've seen memory usage as high as 5GiB per instance.

Per-compiler memory usage for local threads should be the same with FASTBuild as without, but FASTBuild is capable of more parallelism than MSBuild so it's possible you might see higher peak memory usage than before.

From your screen capture, it looks as though you have 32GiB of memory and 24 CPU cores, which is probably not a good balance. The high total memory usage of the compilers will result in paging if it exceeds physical memory available, which would explain both your machine being unresponsive as well as your 100% C: disk usage. 

**Options**

The options in this case that I can see are:
a) limit FASTBuild threads/parallelism with the -jX option (for example -j12 will limit to 12 cores, halving peak memory usage)
b) split your Unity files to reduce peak usage of each compiler instance. I'm not sure if Unreal supports this (you may be able to split only particularly large or problematic libraries if you determine only some are problematic)
c) increase physical memory in the system

**/Zm compiler option**

My understanding is that the /Zm compiler option mostly doesn't do anything in recent versions of MSVC, but when it did, /Zm100 is the default, so specifying that would have no effect anyway. Additionally, it is a compiler flag, so must be passed on the command line, not the environment. At /Zm100 (the default), the maximum memory used would be 75MiB, which is only 1.8GiB so given how much memory pressure your system is under, it doesn't seem like reducing that would have any tangible overall effect.

**Comment by fsfod** [comment] 2022-12-18 10:35
I noticed this as well for Unreal's FASTBuild integration. Looking at there code to run FASTBuild it doesn't appear to have a way set a -j command line option but you can edit the code in ExecuteBffFile method and add a hardcoded -j value in the the FBCommandLine string.

**Comment by Shaggy84675** [comment] 2022-12-18 14:29
Thank you for the detailed info and all the advices!

> **Memory usage used for distributed compilation to ~2GiB, so assuming this hasn't been changed in your bff file:**

If you mean **.DistributableJobMemoryLimitMiB**, then yes I set it in the bff file, but it seems compiler ignores it, because it didn't limit anything
```
Settings 
{
	.CachePath = 'X:\cache'
	.BrokeragePath = 'X:\'
	.DistributableJobMemoryLimitMiB = 512
	.Environment = 
	{
		"PATH=C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31629\bin\HostX64\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64",
		"TMP=C:\Users\Patrik\AppData\Local\Temp",
		"SystemRoot=C:\Windows",
	}
}
```
> **It's not uncommon for individual instance of the compiler to consume hundreds of MiB or even GiB:**

Yes I'm actually aware of that and I found it surprising that it can consume even memory I don't have :) That's why I wanted to ask here if it's possible to reduce it and if that's a good idea or I should rather limit the CPU cores to reduce number of compiler processes/instances. I didn't have problems with memory when I compiled the project without FASTBuild but I saw some of the cl.exe processes also consumed around 1,5 GB of memory, so I guess that's probably because of the better FASTBuild parallelism as you mentioned later.

There comes another question, because I'm still testing everything and even the machine I have I built two weeks ago so I still have no idea how long does the compile work takes. Let's say this machine is 6x more powerful than the remote one I ran FASTBuild worker on as well. Would be better to use FASTBuild with limited number of CPU cores or just native MSBuild compiler without any limitations? Or is it hard to answer, because that all depends on the size and complexity of the project? The remote machine is 6x slower anyway so maybe it doesn't even help with the process that much. And I know FASTBuild have also caching and other stuff what helps with the work too than MSBuild. I think the biggest project I compiled so far was the Unreal source, which took me around 5-6 hours on my old machine (without FB). The remote machine managed to compile it within 9 hours itself (also without FB).

> **32GiB of memory and 24 CPU cores, which is probably not a good balance. The high total memory usage of the compilers will result in paging if it exceeds physical memory available:**

I may buy another 32GiB in the future, but for now 32GiB is gonna be all I have on this machine. And you're right. That's actually true and I was thinking about that paging too.

> **/Zm compiler option**

I've also tried lower values (even /Zm10), but yeah it didn't do anything. Even /Zm100 is the default option, I've seen in the docs, it should be limited to 75MiB so yeah that's why mentioned it with this value. 
I just went through the bff file and I've noticed the compiler options in every action:
![obrazek](https://user-images.githubusercontent.com/1374803/208302805-136351c5-906d-46bf-9611-1edb74a5e398.png)
But 1000 = 750MiB that should be 750 * 24 = 18000 MiB right? Still doesn't seems right.

> **Options**
c) Unfortunately currently not possible
b) If I try to compile the Unreal source, which is probably the main reason for using FASTBuild at this moment, then splitting those files is gonna be probably not doable with thousands of actions
a) This is the solution I tried and it did work, but that leads me back to the question I asked if using limited FASTBuild is gonna be better than not limited MSBuild.

And last question. What's the difference between limiting the CPUs in FBuildWorker and the -j option then? If I limit it in FBuildWorker, shouldn't be already limited to that number?

Also @fsfod - Thank you!

-------------------------------
OT: There's a small thing I've noticed in the FBuildWorker command line options dialog on this line:
https://github.com/fastbuild/fastbuild/blob/0dcc4b326fd070cd616fb71648d240c13124e4d5/Code/Tools/FBuild/FBuildWorker/FBuildWorkerOptions.cpp#L174
It should be:
`" -minfreememory=<MiB>\n"` (missing =)

**Comment by ffulin** [comment] 2022-12-18 23:18
> **.DistributableJobMemoryLimitMiB, then yes I set it in the bff file, but it seems compiler ignores it, because it didn't limit anything**

This setting limits FASTBuild's local memory buffer for preparing distributable jobs. It has no bearing on compiler memory use.

> **I've also tried lower values (even /Zm10)...** 

Base on my experience and interpretation of the documentation:
a) this is a virtual memory address space reservation, and doesn't impact committed memory
b) only relates to memory use of the precompiled header
c) in more recent versions of Visual Studio, this either does nothing or simply provides a starting value which can be exceeded dynamically if needed

So I think modifying this value is unlikely to have any impact on **actual committed** memory usage of compiler instances at all.

From:
https://learn.microsoft.com/en-us/cpp/build/reference/zm-specify-precompiled-header-memory-allocation-limit?view=msvc-170

`Currently, the compiler dynamically grows the heaps as necessary up to a total heap size limit, and allows the precompiled header to comprise multiple address ranges. Now, the /Zm compiler option is rarely necessary.`

**> But 1000 = 750MiB that should be 750 * 24 = 18000 MiB right? Still doesn't seems right.**

As noted above, I think this is a reservation and not n committed value, so tweaking it probably does essentially nothing now.

This value also only relates to one aspect of compile memory usage and doesn't in any way control overall compiler memory usage.

I don't think there is any option you can tweak to reduce memory usage of compiler instances. You can only run less of them at the same time, or split up the code into more Unity blobs.

**What's the difference between limiting the CPUs in FBuildWorker and the -j option then? If I limit it in FBuildWorker, shouldn't be already limited to that number?**

There are two independent CPU limits. One for the local machine and one for each worker.

The local machine can be controlled with -jX on the command line. It controls how many local CPU cores will be used, and by extension how many instances of the compiler can be spawned locally in parallel. If you are exceeding physical memory limits on the main machine controlling the build, this is the one you need to tweak.

Each remote worker can be configured to use a certain amount of CPUs (either via the UI or via the -cpus command line). This has no bearing on the "host" machine's memory usage. For each worker, you'll similarly want this set to balance core count vs physical memory based on the ~2GiB/CPU core rule of thumb, otherwise the worker will perform poorly due to paging in the same way you are seeing on the host.

**Comment by ffulin** [comment] 2022-12-19 22:24
>  **I think the biggest project I compiled so far was the Unreal source, which took me around 5-6 hours on my old machine (without FB). The remote machine managed to compile it within 9 hours itself (also without FB).**

I'm not an expert on Unreal compile times (esp. for Unreal 5.x), but those times seem very high, even for Unreal: perhaps as much as 10x what one would normally expect. Perhaps you were hitting memory limits or other bottlenecks already even with stock MSBuild, but perhaps not bad enough to stop it completing?

> **Would be better to use FASTBuild with limited number of CPU cores or just native MSBuild compiler without any limitations?**

The teams I know using FASTBuild with Unreal get great results with caching and distribution, so if you are able to leverage those in your setup, you can potentially see some very large gains.

Caching requires something like a CI system to prime the cache typically to be useful, but when it does, compilation can be sped up by several orders of magnitude.

Distributed compilation adds some overhead that must be compensated for by having enough additional compute resources to come out on top overall. In some code bases a single CPU core on a remote host is enough to "break even" and anything on top of that accelerates compilation. In other codebases several remote workers are required for a net gain.

I think the only way to know if what gains you will get and whether they are meaningful in your use-cases will be for you to measure successful builds with MSBuild and compare them to FASTBuild ones in scenarios that are important to you. To have useful data in both cases I think it'll be important to ensure you aren't hitting memory limits and paging as that would destroy performance no matter what build system is being used.

**Comment by ffulin** [comment] 2022-12-19 22:32
I stumbled across this post which may be relevant: https://forums.unrealengine.com/t/compilation-taking-twice-as-long-in-ue5-number-of-processes-being-limited/533454/10

It seems to imply that Unreal 5 might use fewer CPU cores than UE4 by design in order to limit peak memory usage and might have some explicit logic for that:
```1>Determining max actions to execute in parallel (4 physical cores, 8 logical cores)
1>  Requested 4 process count multiplier: limiting max parallel actions to 16
1>  Requested 1.5 GB free memory per action, 20.13 GB available: limiting max parallel actions to 13```

Perhaps that is something you can check for in your own test logs.

**Comment by Shaggy84675** [comment] 2022-12-21 19:28
> I'm not an expert on Unreal compile times (esp. for Unreal 5.x), but those times seem very high
Yeah, my old CPU was i5-8600K and my friend told me his compile times are about 30-45 min on Ryzen 9 5950X if I remember correctly, so I think that comparison looks like it makes sense? Also the machine where it took about 6-7 hours is my old server with Xeon E5520 and here's the result from Jenkins:
![obrazek](https://user-images.githubusercontent.com/1374803/208986025-68c63fd6-548c-4114-af3e-e9a0f373b301.png)

I'm actually thinking to use FASTBuild just to speed up the CI jobs on my server and see how that goes.

Anyway! Thank you for all the info and answers, really appreciate it. Like limiting the number of cores with the -j option helped and I think there's no more options for me now, so I'm gonna stick with it until I get more phys. memory. I will also do some tests and see the results with and without FASTBuild with comparison to MSBuild on my main machine. I'm really happy I managed it to work.

**Comment by ffulin** [comment] 2023-01-13 22:30
Thanks for the update. I'll close this issue for now as it seems as resolved as it can be.

**Closed** 2023-01-13 22:30 UTC
Labels: Question
