### ISSUE TITLE
-report segfaults

### ISSUE THREAD

**Issue by trufae** [fastbuild/fastbuild#29] opened 2015-07-05 15:33 UTC

**Comment by ffulin** [comment] 2015-07-05 15:42
Can you please provide some more details?
 * What platform are you running on?
 * What version are you running?
 * What is the full command line you are using?
 * If you have a bff file that you've created which can reproduces the crash, are you able to provide it here (or send it to fastbuild@fastbuild.org)?

**Comment by ffulin** [comment] 2015-07-05 16:00
I guessed from your other ticket that you are running on Linux.

I've reproduced the crash (caused by some functionality not yet implemented on Linux).

Thanks for the report.

**Comment by ffulin** [comment] 2015-07-05 21:56
I have fixed the bug (Linux and OS X) in the main perforce branch.  The fix will be part of v0.84.
I'll leave this issue open until that version is released.

**Comment by trufae** [comment] 2015-07-06 13:04
I got the crash on osx. But i guess it was a generic issue. I was testing
it and filling issues without checking the source. I'll do more testing and
such in the following days. I have some ideas to make fb better

**Comment by trufae** [comment] 2015-07-06 13:04
Thanks

**Comment by ffulin** [comment] 2015-07-29 05:49
v0.84 has now been released.  Closing this issue.

**Closed by ffulin** 2015-07-29 05:49 UTC
