### ISSUE TITLE
Improve management of the cache directory

### ISSUE THREAD

**Issue by nre-ableton** [fastbuild/fastbuild#268] opened 2017-07-28 13:30 UTC
Currently FASTBuild doesn't provide much tooling to clean the cache, and it doesn't have an option to set a maximum cache size (please correct me if I am wrong on either of these points). This means that after awhile, the cache can grow to a very large size. As far as I can tell, the only way to "clean" the cache is to simply remove the entire directory, which can take a long time if it has grown to a large size, and then another long wait during the inevitable full rebuild afterwards.

I can think of a few ways to improve the situation here. First, the `FBuild` tool could have an option to remove old files from the cache (where "old" is somewhat arbitrary, but for example, could mean files that haven't been touched in >30 days). Currently, FASTBuild provides a `-cache [read|write]` option, so `-cache [read|write|clean]` might fit in nicely there.

Another possibility is that FASTBuild could have a configuration setting for the maximum cache size, which would force the `FBuild` tool to remove older files in a FIFO-type manner to keep the cache around this size during builds. While this is most convenient from the user's standpoint, I realize that this might impose an additional unwanted performance cost on build times.

Both of these ideas are shamelessly lifted from the `ccache` tool. I'm definitely not advocating that FASTBuild should behave like `ccache` in all circumstances, but at least when it comes to cache management, it would be appreciated if FASTBuild shared some of the same features that `ccache` does in this respect.

**Comment by ffulin** [comment] 2017-08-01 03:19
I've been thinking about this problem for some time.

As you say, maintaining a particular size of cache while building would be prohibitively expensive, (since we can't assume anything about the state, we'd have to do a full scan). My thinking has been to provide an explicit command to invoke to prune the cache, where you could specify a size such in gigabytes. I would expect that you would schedule a job to run nightly with this command, either in your build system or as a cron job somewhere. It would then trim the cache to that size, starting with the oldest files first.
Something like:
```
fbuild.exe -cachetrim 500
```

**Comment by nre-ableton** [comment] 2017-08-01 08:29
@ffulin I like the idea of a `-cachetrim` option. What criteria would be used for choosing the files that remain in the cache? I'm assuming that timestamp would play a factor here.

**Comment by ffulin** [comment] 2017-08-02 04:49
My plan was to use the file creation time, simply deleting oldest files first. (The last access time would of course be preferable, but this is rarely valid in modern file systems so creation time seems the next best thing). Scripts I've seen tend to use the creation time and it works well in practice as things tend to naturally be re-populated as needed.

**Comment by BrodyHiggerson** [comment] 2017-08-14 00:53
Would you consider a way to clean the cache in a more specific way? For example, if I'm building massive project A and small project B, and find that there's something funky going on with project B's cached objects, I can't clean for just that project without wiping out A's cached objects and then having to spend a long time recreating them.

**Comment by ffulin** [comment] 2017-08-16 04:18
@BrodyHiggerson There isn't really any way to associate a particular object with a particular project. In a way, it's sort of meaningless to even try. Let's say hypothetically user A compiles project A's C:\code\test.cpp and user B compiles project B's C:\code\test.cpp, they (assuming all settings are the same) actually be the same object in the cache. Even if that's a contrived situation, it's still hard to imagine *how* you'd even define an object as belonging to a project in a way that is useful.

If you really want to isolate the cache objects for your projects, the only way to achieve it that I can think of would be for each project to have a different cache directory.

Of course, you should never find yourself in a situation where you question the validity of the cache. The cache is designed to be written in a way that you cannot end up in a bad state. If the cache is ever in a bad state, that could only be caused by:
a) corruption of the cache files, which should be detected by the basic sanity checks that exist when retrieving from the cache an thus still be "safe"
b) a bug in FASTBuild, which we'd want to get to the bottom of right away

**Comment by BrodyHiggerson** [comment] 2017-08-16 04:32
@ffulin Good points. I guess I was thinking along the lines of those times when rebuilding a project cleanly fixes some otherwise-unexplainable error or issue with linking (we've all had those, I think). I guess if we're just storing objects in the cache, we can guarantee that those objects are individually exactly what they should be, and a rebuild would just relink them, hopefully fixing the aforementioned situation.

In regards to the projects - I totally agree, the cache wouldn't know which project was which. I more meant if FASTBuild would support clearing by hash, some other tool invoking it could allow you to 'clean cache for project' and would just send over the hashes of its files? I'm not up on how those hashes are calculated so maybe that's crazy but just an idea :)

**Comment by nre-ableton** [comment] 2017-08-16 07:06
@BrodyHiggerson a possible workaround for you could be using different FASTBuild caches per project via the `FASTBUILD_CACHE_PATH` environment variable.

**Comment by ffulin** [comment] 2018-01-01 20:22
I've implemented -cacheinfo and -cachetrim (https://github.com/fastbuild/fastbuild/commit/5b4436999c76e458f2558aab86a1d7e99409b518). The former provides a non-destructive summary of the current state of the cache, while the latter trims the cache to the desired size as previously discussed. These options will be in the next release (v0.95). I'll keep this issue open until that version is released.

**Comment by ffulin** [comment] 2018-02-04 21:24
v0.95 has now been released and includes the new -cachetrim and -cacheinfo options. Thanks for your feedback on FASTBuild!

**Closed by ffulin** 2018-02-04 21:24 UTC
Labels: Enhancement, In Next Version
