### ISSUE TITLE
UnityInputExcludePath doesn't seem to be correctly parsed when UnityInputPath finishes with "\.."

### ISSUE THREAD

**Issue by Laefy** [fastbuild/fastbuild#543] opened 2019-04-01 17:49 UTC
Let's consider:

.UnityInputPath = '$CurrentBffPath$'
.UnityInputExcludePath = '$CurrentBffPath$\\A.cpp'

Then A.cpp will not be builded.

However, let's consider:

.UnityInputPath = '$CurrentBffPath$\\..'
.UnityInputExcludePath = '$CurrentBffPath$\\..\\A.cpp'

Then A.cpp will be builded (but it shouldn't).

**Comment by ffulin** [comment] 2019-04-02 02:46
The .UnityInputExcludePath specifies a path, not a single file, so in your examples, you are effectively doing this:
```C++
.UnityInputExcludePath = '$CurretntBffPath$\A.cpp\'
```
and
```C++
.UnityInputExcludePath = '$CurretntBffPath$\..\A.cpp\'
```
In my tests (as expected) neither of those exclude a file called A.cpp.

If you want to exclude specific files, you can use the .UnityInputExcludedFiles

**Comment by ffulin** [comment] 2019-04-02 03:02
Note that while I was not able to reproduce a problem with the information you provided (in v0.97), it's possible something about your setup means you were encountering a problem that has been fixed in the dev branch (https://github.com/fastbuild/fastbuild/commit/e93fd0deaa942bc094842b50638eb06f1db58389)

**Comment by Laefy** [comment] 2019-04-02 08:59
My bad, it was indeed .UnityInputExcludedFiles that we used.
I'm gonna show our actual state and the different cases. We have a project which is built for different platforms P1, P2 and P3, and some sources files which are common to all these platforms. The hierarchy is the following:

- ProjectRoot\
    - P1\
        - P1 source files
        - P1.fastbuild.bff
    - P2\
        - P2 source files
        - P2.fastbuild.bff
    - P3\
        - P3 source files
        - P3.fastbuild.bff
    - common source files

--------------------------------------------------------------------------------------------------

P1 should include the common source files and the files in P1, and exclude P2 and P3.
The .bff for P1 contains therefore the following lines:

    .UnityInputPath            = '$CurrentBffPath$\..'
    .UnityInputExcludedFiles   = {
                                     '$CurrentBffPath$\..\p2\[p2 source files]', // one line for each file to exclude
                                     '$CurrentBffPath$\..\p3\[p3 source files]'
                                 }

In this case, the resulting unity.cpp file includes all files from ProjectRoot, including P2 and P3 source files.

--------------------------------------------------------------------------------------------------

However, if we replace .UnityInputPath with the actual absolute path to ProjectRoot:

    .UnityInputPath            = '[absolute path to ProjectRoot]'
    .UnityInputExcludedFiles   = {
                                     '$CurrentBffPath$\..\p2\[p2 source files]', // one line for each file to exclude
                                     '$CurrentBffPath$\..\p3\[p3 source files]'
                                 }
Then the resulting unity.cpp file only includes the common source files and the ones from P1, effectively excluding  P2 and P3 source files.

--------------------------------------------------------------------------------------------------

Now, if we add p1\.. to the end of .UnityInputPath:

    .UnityInputPath            = '[absolute path to ProjectRoot]\p1\..'
    .UnityInputExcludedFiles   = {
                                     '$CurrentBffPath$\..\p2\[p2 source files]', // one line for each file to exclude
                                     '$CurrentBffPath$\..\p3\[p3 source files]'
                                 }

P2 and P3 source files are not excluded anymore from the unity.cpp.

--------------------------------------------------------------------------------------------------

So the observation here is that, when the .UnityInputPath finishes with '..', the .UnityInputExcludedFiles   is not computed or at least not computed as expected.

Again, sorry for the error in the previous message.
The repro steps of this message were made on v0.96.

**Comment by ffulin** [comment] 2019-04-03 01:59
Thanks for the extra info. The problem is indeed the bug I mentioned - paths ending with .. were not being canonicalized properly (in this case the UnityInputPath), so when compared to against your exclusions, the exclusions didn't match (as they were canonicalized correctly)

The fix (https://github.com/fastbuild/fastbuild/commit/de79bdfea59d101af85b0b5ab6fe628ab5d8aa12) will be in the next release (v0.98). I'll leave this issue open until that version is released.

**Comment by Laefy** [comment] 2019-04-03 08:46
Thank you very much :)

**Comment by ffulin** [comment] 2019-05-02 05:44
v0.98 has now been released and contains a fix for this issue.

**Closed by ffulin** 2019-05-02 05:44 UTC
Labels: Bug, Resolved In Next Version
