### ISSUE TITLE
PCH not being rebuilt.

### ISSUE THREAD

**Issue by billw2012** [fastbuild/fastbuild#672] opened 2019-12-07 19:04 UTC
I have to force rebuild after most changes to headers in my PCH at the moment.
Project fbuild is here: https://raw.githubusercontent.com/caveman2cosmos/Caveman2Cosmos/master/Sources/fbuild.bff

**Comment by ffulin** [comment] 2019-12-07 19:34
I took a look at your config and nothing stood out as being an obvious cause of the problem you describe. There are a few possible paths forward:

a) debug yourself with -showdeps and -verbose
 - -showdeps shows the dependency graph so you can verify the dependencies are not missing
 - -verbose shows the reason for building and might provide some insight

b) debug yourself inside FASTBuild
 - the core DetermineNeedToBuild function is likely the best starting point

c) create a self contained and simplified repro case and send it to me
 - if you can create a small stand-alone repro I can investigate the issue

**Comment by billw2012** [comment] 2019-12-08 16:22
I tried option a) it shows dependencies are almost entirely missing for my PCH, it only has a set of windows header files.
So I set up for option b). First problem I hit is related to the one in #666: 
![image](https://user-images.githubusercontent.com/1453936/70392299-9e6f2000-19d6-11ea-9e12-162307f91736.png)

**Comment by billw2012** [comment] 2019-12-08 16:49
Next problem, it has assumed my PCH cpp file is "CvGameCoreDLL.cpp" just because my PCH header file is "CvGameCoreDLL.h" even though I passed the correct cpp file to the PCH command ("_precompile.cpp").

**Comment by billw2012** [comment] 2019-12-08 18:39
Had to disable the cache to get this working. I was only seeing 17 out of 100s of deps on my PCH file when using the cache (the windows headers i mentioned).

**Comment by ffulin** [comment] 2019-12-10 02:44
When using the cache (or distributed compilation) with MSVC, a different path is taken (using the preprocessors instead of /showIncludes) to gather dependency information. This might be interacting with something specific about your setup. PCH use with and without the cache normally works fine.

The "baseDir" you show looks pretty suspect. I'd expect the path to be a canonical one at that point. I'm not sure if the issue in #666 is related, but there's certainly something funky going on.

Looking again at your bff and the info you've provided, the cpp and header names being inconsistent might be a good avenue to investigate. In all the working cases I know of (my uses and the tests), the .h, .cpp, .pch and .pch.obj all have the same "root" name, which isn't the case in your setup.

**Comment by billw2012** [comment] 2019-12-14 16:59
> Looking again at your bff and the info you've provided, the cpp and header names being inconsistent might be a good avenue to investigate. In all the working cases I know of (my uses and the tests), the .h, .cpp, .pch and .pch.obj all have the same "root" name, which isn't the case in your setup.

I just confirmed that it is a combination of using the cache and having the pch name differ from the cpp name, i.e. CvGameCoreDLL.cpp, CvGameCoreDLL.h, but C2C.pch. If I use CvGameCoreDLL for all the names it works with the cache. 
This should be noted in the docs as it differs from the compiler requirements, where any name can be used for any of these items.

**Comment by ffulin** [comment] 2019-12-15 00:16
This isn't a deliberate restriction, and I don't think it should be required. I'll need to investigate further, but I would consider this as a bug.

**Comment by ffulin** [comment] 2020-01-19 18:57
PR https://github.com/fastbuild/fastbuild/pull/681 fixes an issue where the PCH filename was not used consistently when it differed in the way your example does. I'm not certain this fixes this issue, but it is likely related.

**Comment by ffulin** [comment] 2024-02-24 02:48
It seems the fix mentioned would have resolved the inconsistency with using a differing name for the pch which appears to be the root cause of this issue. Without any other leads or repro cases, I'm going to close this as fixed. We can re-open or create a new issue if problems still persist.

**Closed by ffulin** 2024-02-24 02:48 UTC
Labels: Bug, Need More Info (or Blocked)
