### ISSUE TITLE
(New Feature) FASTBuild Monitor

### ISSUE THREAD

**Issue by yass007** [fastbuild/fastbuild#127] opened 2016-08-15 21:15 UTC
Hi @ffulin,

I'm opening this ticket so we can discuss how to integrate the monitor VSIX that @liamkf and myself built for FASTBuild. 
The goal of this was to add a visualization tool that allows to see what's really going on between machines, and link performance stats with the distributed build events. 
So it could basically be used as a viewer, profiler and also a high level debugger for FB.

First of all I would like to gather your feedback on the code changes that are required on the FASTBuild side: We have tried to isolate our changes as much as possible with #ifdefs and command line options (see #if defined(FBUILD_MONITOR) and "-monitor").

The code has been branched from the dev Branch and is available here: https://github.com/liamkf/fastbuild
Make sure you look at the **visualizer** branch inside that repo.

The monitor code and VSIX package can be found in https://github.com/yass007/FASTBuildMonitor.
There are some "work-in-progress" instructions on how to get up and running with it. 
It should be pretty simple once you get the VSIX installed and the custom FBuild.exe compiled and deployed.

Just to show a bit of how the app looks/works here is a quick video that I captured: https://youtu.be/saxFpmNq_Vw

And some screenshots (you've probably seen them in other posts):
![visualizer](https://cloud.githubusercontent.com/assets/2611324/17679769/eaf92a46-630a-11e6-8bbb-e9a9a6a057bf.png)
![fbuild caching pchs](https://cloud.githubusercontent.com/assets/2611324/17679779/f1e24b94-630a-11e6-9157-c2556ccc52b6.png)

Of course let me know if you have any question or feedback!

Cheers

**Comment by ffulin** [comment] 2016-08-17 05:12
Thanks!  I'll find some time to look at your changes and the plugin so we can work out the best way to move forward.

**Comment by ffulin** [comment] 2016-09-04 03:35
I've started looking at the code, beginning with the FASTBuild modifications. They look pretty straight forward and I can probably just integrate them. We can keep them on the command line switch.

I have a few questions about some of the code changes though:

**1: getnameinfo in TCPConnectionPool.cpp**
Did you profile the cost of this?  I've had issues with really slow network lookups, so I've deliberately avoided and non-critical name resolution like this in the past. No big deal if you haven't profiled it yet. I'll do that.

**2: Showing source file names**
FASTBuild shows the object files names generally instead of the source file names in order to disambiguate when you are building multiple configurations at the same time (something that FASTBuild excels at). i.e. you can see Debug/Thing.obj & Release/Thing.obj instead of two Thing.cpp instandes.  I've previously considered a command line option to show the source instead.  Any thoughts on this?

**3: break in Server.cpp**
This code was added to the end of the FinalizeCompletedJobs function in Server.cpp:
```C++
if (localTimer.GetElapsedMS() > Protocol::SERVER_STATUS_FREQUENCY_MS)
```
Can you tell me a little more about what issue this was addressing?  Seems like perhaps you saw this function take more than the timeout frequency (previously 5s) to be called and maybe you saw workers being disconnected because of that? If that's the case, seems like I should consider any traffic to track when it last heard from the worker rather than just the MsgServerStatus.

**4: SERVER_STATUS_TIMEOUT increased to 50000**
It used to be 5000ms. I guess you were seeing workers dropped sometimes, even with the changes above?  Maybe 5s is too low, but maybe 50s is too high, especially if I make the change above?

Anyway, any insight into these items would be helpful.

I'll look into the VS plugin next.

**Comment by ffulin** [comment] 2016-09-04 20:07
I've got the VS plugin working locally and confirmed my integration of the "liamkf/fastbuild" branch works correctly! I've got a little more cleanup to do and I'll submit it to the dev branch.

A couple things I've noticed:

**getnameinfo can be really slow**
As I suspected, getnameinfo can be really slow.  On my local network it can take as long as 5 seconds!  This translates directly into a delay of all distributed compilation by this amount. We can actually remove this lookup because the higher level code already has the host name and has converted it into an address to call this lower level code: so the higher level code (Client.cpp) can just record the host name.  I'll make this change.

**Flog::Monitor and Flush() adds non-trivial overhead**
The Flog::Monitor function adds non-trivial overhead and can cause lengthy stalls when it calls Flush (1 second or more is pretty common). In the worst case, it stalls all threads for this long if they are all trying to all write to the monitor log (pretty common during pre-processing). Since this only impacts users who have opted-in with "-monitor" I think it's ok to integrate as is to progress things along, but I think we'll want to shift the monitor output to another thread. I had thought previously about moving the regular console output to another thread as a small optimization (same general problem, but much smaller overhead) but it didn't seem like super huge gain, but I might now combine that with this work.

**Comment by ffulin** [comment] 2016-09-05 19:24
I've integrated the -monitor changes into the dev branch: https://github.com/fastbuild/fastbuild/commit/f0f4e37f24b18ac6450629f84f2290d536412e1e

Notes:
* **Removed getnameinfo** - The Client now stores the hostname in the structure we use to track connections prior to address resolution, so we can just use that for free.
* **Removed flushes of monitor log** - I removed the flushing of the monitor log.  It doesn't seem necessary (everything still operates in real-time) and it eliminated the performance concerns.
* **Removed FBUILD_MONITOR define** - I removed this define. The code is always available, and toggleable with the -monitor command line. There is as close to zero overhead as is possible when -monitor is not used (everything wrapped up in the FLOG_MONITOR define.
* **Cross-platform** - I made the code compile/work on Linux and OSX as well.  Naturally there is no useful way to visualize, but this opens up that possibility in the future.
* **Timeout changes not integrated** - For now I've not integrated the changes to timeouts for remote workers until I can better understand why they are needed and/or improve the timeout logic.

I also made some notes about things that need investigation/fixing (mix of visualizer and FASTBuild changes will be needed):
* **Not all items appear in the visualizer** - Tests are the most notable example. Should be trivial to fix.
* **Mouse over tooltips don't match items** - If I mouse over items in the visualizer, the tooltips don't match the filename shown (sometimes empty, sometimes a completely different file)
* **Work incorrectly shown as being done on remote workers** - When I build FASTBuild, the visualizer shows preprocessing being done on the remote worker, which is impossible.  Might be related to the tooltip issue above (something being out of sync)?
* **Remote workers shown doing more work than they actually do** - FASTBuild workers request extra jobs than they have CPU cores to keep the remote CPUs fed.  This means a 4 core machine might have 5 jobs, but it's really only compiling 4.  Not sure about the best way to fix this.

One final thing - what are your thoughts on the long-term maintenance of the visualizer plugin? Is this something you want to maintain as a 3rd party, or something you'd like to roll into FASTBuild itself?

**Comment by ffulin** [comment] 2016-09-06 00:11
I've made some changes to the -monitor behaviour which fixes two of the issues I was seeing: https://github.com/fastbuild/fastbuild/commit/e6cf222bc8a4864952626ff2017d87f700caeb26

Fixed:
* **Not all items appear in the visualizer** - I added the Test() to the list of items.
* **Work incorrectly being shown as being done on remote workers** - This turned out to be because we were using the cpp file name for the name of the task, which is not unique (can compile the same cpp file multiple times in a build). I switched everything to use the target name. Perhaps we should use the target as the key, but provide a secondary filename for use in the UI?

**Comment by yass007** [comment] 2016-09-07 13:28
Thanks for the feedback, the integration and the profiling, Great work!

I have synced to the latest DEV branch and confirm that I'm seeing exactly what you are reporting so we are on the same page :).

Here are my answers to the pending questions:

**Showing source file names**
I think going with the target file name instead of the source name is simpler and is fine by me.
I changed the visualizer to color .obj files differently than the rest. Maybe that's sufficient for now but we could easily add an extra NodeType parameter to the JOB event to control the coloring.

**Work incorrectly being shown as being done on remote workers**
Yes we are currently using the (Target) full path as the Job Key and the file name for UI text. The Job Key has to be unique between the Jobs currently in flight otherwise conflicts occur.
 As you are suggesting, if needed we could easily split the two and provide a different string for the UI text.

**Mouse over tooltips don't match items**
Should be fixed by v0.96  https://github.com/yass007/FASTBuildMonitor/commit/c46b8f9850317fe1d28748296f5e1836bf0b040c
Also fixed the system graphs and the time bar not being updated.

**Remote workers shown doing more work than they actually do**
Yeah... So that was the dilemma I had between being super precise and starting to add more status network messages to communicate exactly what is being executed on the remote workers and when vs living with this imperfection and keeping things simple.
For a first pass I decided to go with the simplest option which if is showing the state of the remote queue but I'm totally open to implement a more precise option if we think about something that doesn not add a significant overhead when there are hundreds of workers in the worst case ?

**Timeout changes not integrated**
It's good that you haven't integrated those as they were not related to the monitor.
But yeah we had to face a number of timeout issues on a our (little) distributed setup: 2 laptops on WIFI + 2 PCs on LAN and building the huge Unreal unity files and transferring the giant object files over a slow network.
We recognize our setup is not representative of an optimal build farm but nonetheless other individuals or small companies could face similar issues.
So yeah we had to trace the source of the timeouts and fix them by increasing the time thresholds or the code hack on the server.cpp above to handle cases where multiple big obj files where queued for a transfer.
We'll try to open separate issues for these timeouts with more info.

**One final thing - what are your thoughts on the long-term maintenance of the visualizer plugin? Is this something you want to maintain as a 3rd party, or something you'd like to roll into FASTBuild itself?**
We are very open about this.
Since the monitor and FASTBuild share a common protocol it would make more sense if they are packaged and distributed together + it would make it easier for everybody to contribute to both projects.

**Comment by ffulin** [comment] 2016-09-10 19:12
**Mouse over tooltips don't match items**
Cool!  I'll grab the latest version.

**Timeout changes not integrated**
Operating over Wi-Fi is certainly sub-optimal, but should be supported. I think there might be scope for making the behaviour more intelligent with respect to the keep-alive, and perhaps even making it just a lot longer is a good change. Agree that forking this into another ticket is a good way to proceed.

**Packaging plugin with FASTBuild**
I agree this would be ideal. I have been thinking about making a plugin to improve some other aspect of FASTBuild integration in VS, so this could all get nicely merged together, and releasing the plugin versioned along with FASTBuild would be ideal.
The only issue I see is the MIT license you have used, which is more restrictive than the FASTBuild one (which doesn't require any attribution). Merging the plugin code into the FASTBuild code would effectively make FASTBuild inherit those license terms (at least for some of the code) and as a result so would every downstream user.
FASTBuild contains some other code (like LZ4) which has differing licensing terms, but it is trivially isolatable in a way that I'm not sure this plugin will be.
Would you be open to releasing your code under alternative licensing terms, like those used by FASTBuild? It might be possible to work this out without doing that, but it would greatly simplify things.

**Comment by ffulin** [comment] 2018-04-29 00:54
@yass007 - I've been pondering the visualized for a while, and I think I will no longer attempt to integrate it into the the FASTBuild repo. In the end, I don't see a way to have it part of the repo without introducing a dependency on msbuild (due to the use of xaml). Additionally, it's pretty clear I don't really have the bandwidth to maintain such a large feature, at least not when there is still so much to do in the core of FASTBuild. I think it's best if this remains a stand-alone product. Sorry :(

**Comment by ffulin** [comment] 2018-07-01 18:14
Closing unactionable issue > 30 days old.

**Closed by ffulin** 2018-07-01 18:14 UTC
Labels: Enhancement
