### ISSUE TITLE
Compiler messages character encoding seams to be broken

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#72] opened 2015-11-26 02:24 UTC
The dev branch version of Fastbuild outputs this in my french VS2015 :
````
1>  LINK : .netmodule ou module MSIL compilÚ avec /GL trouvÚá; redÚmarrage de l'Údition de liens avec /LTCGá; ajoutez /LTCG Ó la ligne de commande de l'Údition de liens pour amÚliorer les performances de l'╔diteur de liens
````

I did not check the code, but could this be related to recent changes ?

**Comment by ffulin** [comment] 2015-11-26 18:48
No recent changes spring to mind as being related to this. Unlike the ObjectNode, the LinkerNode doesn't do any processing of the output at all, so I'm not even sure what could be wrong.

I tried to reproduce this, but I can't seem to persuade my linker to operate in French outside of Visual Studio, in either FASTBuild or directly invoking from the command line. It seems to either ignore the language setting (which is set by the IDE in a registry key). I tried to replace the English localized DLLs (1033) with the French ones (1036) the compiler starts emitting messages in French, but the linker just starts printing blank lines.  Very strange.

I tried to reproduce this in a regular Visual Studio solution (no FASTBuild involved) and I get a different, but still wrong output:
```C++
1>  Warnings.obj : .netmodule ou module MSIL compilé avec /GL trouvé ; redémarrage de l'édition de liens avec /LTCG ; ajoutez /LTCG à la ligne de commande de l'édition de liens pour améliorer les performances de l'Éditeur de liens
1>  GΘnΘration de code en cours
1>  Fin de la gΘnΘration du code
```

(For reference I'm using VS2015 - Version 14.0.23107.0 D14REL, with the French language pack installed)

I think I'll need your help to debug this issue.
 - Can you please confirm what the output of an empty Visual Studio test project looks like (with Release and LTCG removed from the linker to generate the warning)?
 - Any info on your setup (exact version, language pack(s) and operating system language) would be really helpful
 - If that doesn't help narrow it down, I might need you to try to debug it so we can see if the strings are bad as returned by the linker, or if FASTBuild is corrupting them somehow

**Comment by ffulin** [comment] 2016-07-31 18:24
Hello :) Did you manage to resolve this issue, or get any more info that might help us work out what's going on?

**Comment by poppolopoppo** [comment] 2016-08-03 22:42
Hi !
The text is correctly displayed with Visual 2015 Version 14.0.25424.00 Update 3,
So I kinda gave up on understanding what happened :]
But you might consider this issue as resolved

**Comment by ffulin** [comment] 2016-08-05 03:36
Cool - sounds like it was an issue with VS2015 itself.  Closing.

**Closed by ffulin** 2016-08-05 03:36 UTC
Labels: Bug

**Comment by poppolopoppo** [comment] 2016-08-29 00:29
Erf, I got the same errors again.
I don't know what changed since last time.
I'll take a look...
