### ISSUE TITLE
How to include bff file generated by external tool if exists

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#902] opened 2022-05-08 10:59 UTC
I have a server project, and its fbuild.bff looks like:
<pre>
#if file_exists("additional.bff")
    #include "additional.bff"
#endif
</pre>
This additional.bff file is generated by external tool, so I add a PreBuildDependencies to an Exec as a build step.
But when FASTBuild pasring the fbuild.bff file, this additional.bff is not generated yet. How can I include this file?

**Comment by ffulin** [comment] 2022-05-14 05:10
The bff files describe the rules for a build. They are parsed before the build starts (and parsing is skipped if they have not changed).

If you modify the bff files as a side effect of the build, those changes will not take effect until the next build (they will be reparsed at the start of the next build)

It sounds like what you're trying to do simply won't work (by design). It's somewhat akin to compiling an running a custom executable in a Visual Studio or XCode project and having that executable modify the project files (possible, but they similarly wont take effect until you perform another build)

If you can provide some more details about the result you're aiming for I may be able to provide some suggestions.

**Comment by ffulin** [comment] 2022-11-26 05:29
Closing this issue for now as "answered". If you have some followup questions or I've misunderstood your question please let me know.

**Closed by ffulin** 2022-11-26 05:29 UTC
Labels: Question
