### ISSUE TITLE
Older timestamp does not trigger a build

### ISSUE THREAD

**Issue by aganea** [fastbuild/fastbuild#407] opened 2018-03-30 17:01 UTC
Hi @ffulin,
We have a case in our build system where user can submit preflight changelists, to compile before actually commiting. The preflight can occur arbitrarily on any build machine; those build machines happen to also incrementally build the regular commited changelists. Given that the preflight changelist do not enable a full rebuild, but rather trigger an incremental build, there are cases where files aren't compiled, because the preflighted files are older that those already compiled.

Looking through the code this doesn't look trivial to fix, as (almost) everything assumes a node is "new" only if its timestamp > stored timestamp. 

The workaround for us is to touch the preflighted files to Date.Now.

I'm torn between "this is by design, it isn't a real issue" and "this might happen to someone else" ;-)

**Comment by ffulin** [comment] 2018-04-10 05:31
This is a limitation of the current dependency engine. It is by design, but it was a poor original design choice that prevents fixing at least one other issue. I plan to change the way dependencies are managed in some future refactoring such that rebuilds will occur when the timestamp changes at all. I'll leave this issue open to track this problem until that refactor takes place. Thanks for reporting the issue.

For now, I don't have a better suggestion for a work-around than the one you've already implemented.

**Comment by ffulin** [comment] 2019-11-24 02:14
The dependency engine has been improved and now copes with timestamp changes in any direction (https://github.com/fastbuild/fastbuild/commit/735ba92dfa2d37f0d53dce285a120af091903808). This improvement/fix will be in the next release (v1.00). I will leave this issue open until that version is released.

**Comment by ffulin** [comment] 2020-05-04 01:46
v1.00 has now been released. It includes improvements to the dependency engine that fixes this issue (and others).

**Closed by ffulin** 2020-05-04 01:46 UTC
Labels: Bug, Resolved In Next Version
