### ISSUE TITLE
[0.96] Blue Screen using -fastcancel

### ISSUE THREAD

**Issue by Rseding91** [fastbuild/fastbuild#610] opened 2019-06-05 03:52 UTC
I've had the "fastcancel" option enabled for 3~ months now and today while doing my usual rounds of compile-until-error, fix, repeat Windows 7 blue screened on me.

Normally I wouldn't blame a given program for a blue screen (especially something like fastbuild) but looking into the BSOD it specifically says this:

> CRITICAL_OBJECT_TERMINATION (f4)
> A process or thread crucial to system operation has unexpectedly exited or been terminated.
> ...
> FAILURE_ID_HASH_STRING:  km:x64_0xf4_csrss.exe_bugcheck_critical_process_terminated_by_fbuild.exe_2a9d1060_analysis_inconclusive

Full WinDbg analysis: https://www.dropbox.com/s/rsni7mlw3l1wr7e/WinDbg.txt?dl=0
Minidump of the BSOD: https://www.dropbox.com/s/mipq773dijg0nuh/060419-12480-01.dmp?dl=0

I also have the full MEMORY.DMP that the BSOD process generated but it's 1.76 GB so unless it ends up being needed I'll just hold onto it.

**Comment by Rseding91** [comment] 2019-06-05 04:21
Note: I would attempt to update and see if the issue is fixed in the newer version(s) but considering it took 3+ months of use before this happened once I don't think that's a viable scenario. Also, I looked at the patch notes for the newer versions and they don't list anything about -fastcancel.

**Comment by ffulin** [comment] 2019-06-06 01:43
FASTBuild v0.97 had a bug fix:
```Fix occasional build failure with error 0x1 when a distributed race is won```
part of which included the following fix:
``` - due to pid re-use, the process hierarchy could be incorrectly walked in a cycle, causing incorrect child process termination```

I'm surprised that FASTBuild would be able to terminate a critical system process, since I'd expect that would require some elevated privileges, but that bug seems like a good fit for what you saw.

**Comment by Rseding91** [comment] 2019-06-06 02:30
pid re-use was my theory as to what triggered it (killing the wrong process because it thought it was one of the child worker processes).

If you're seeing this issue was fixed through the other bug fix then this can be closed. I just wanted to mention it in case it wasn't.

**Comment by ffulin** [comment] 2019-06-06 03:07
I took a look a the minidump you linked, but I didn't manage to get any conclusive proof that it was this code path. It seems the dump is well after the root cause.

I think it makes sense to close this as fixed. If you ever see it again with a newer version, we can re-open and try to investigate further. Thanks for letting me know about the problem!

**Closed by ffulin** 2019-06-06 03:07 UTC
