### ISSUE TITLE
CopyDir broken in 0.93?

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#224] opened 2017-03-23 18:08 UTC
Is CopyDir broken in 0.93?

```
C:\dev>%FASTBUILD_ROOT_DIR%\FBuild.exe ProjectName_ExampleApp-CopyExeToVSOutputDirectory-x64-Debug
Node 'C:\dev\Build\Output\VSOutputDirectory\x64-Debug\ProjectName_ExampleApp.exe' is not a CopyFileNode (type: File)
FBuild: Error: BUILD FAILED: ProjectName_ExampleApp-CopyExeToVSOutputDirectory-x64-Debug
Time: 2.093s
```

Here's the code for the CopyDir node:

```

.OutputOffset		= '$Platform$-$Config$'
.OutputBase			+ '/$OutputOffset$'
.AbsoluteOutputBase = '$BuildOutput$/$OutputOffset$'
.ThisConfigVSOutput = '$BuildOutput$/VSOutputDirectory/$Platform$-$Config$/'
.ThisConfigVSInterm = '$BuildOutput$/VSIntermediateDirectory/$Platform$-$Config$/'

	CopyDir( '$ProjectName$-CopyExeToVSOutputDirectory-$Platform$-$Config$' )
	{
		.SourcePaths			= { '$OutputBase$/$ProjectName$/' }
		.SourcePathsPattern		= { '*.$ExecutableExt$' }
	#if CONFIG_IS_MSVC
		.SourcePathsPattern		+ { '*.pdb' }
	#endif // #if CONFIG_IS_MSVC
	#if CONFIG_IS_HTML5
		.SourcePathsPattern		+ { '*.js' }
	#endif // #if CONFIG_IS_HTML5
		.SourcePathsRecurse		= false
		.Dest					= '$ThisConfigVSOutput$'
		.PreBuildDependencies	= '$ProjectName$-EXE-$Platform$-$Config$'
	}
```

**Comment by ffulin** [comment] 2017-04-29 18:58
I'm not seeing any regressions in the CopyDir test, though the internals of CopyDir were changed in v0.93.

It is possible that the refactor is detecting a configuration issue that was slipping through undetected previously. Specifically, this error:
```C++
Node 'C:\dev\Build\Output\VSOutputDirectory\x64-Debug\ProjectName_ExampleApp.exe' is not a CopyFileNode (type: File)
```
means that something in your bff already defined the destination of the copy before the CopyDir rule was hit. 

My guess is that you have another rule that references the copied exe. The problem with that is that this causes a broken dependency chain - FASTBuild doesn't know that the CopyDir has to happen before the subsequent rule, because the CopyDir is evaluated at build time, while a single Copy is evaluated at config parse time. 

That setup might have worked before, but that was actually a bug, because it was unsafe (the operations might have executed in the wrong order - which could result in incredibly difficult to diagnose problems). The error is not particularly intuitive, but sadly there's isn't an obvious way to improve it in this situation.

Is it possible there is something like that in your bff (something using the destination exe copied by CopyDir as an input)?  If so, the fix would be to make the thing that copies the exe an excplicit Copy, as opposed to a CopyDir.

**Comment by ffulin** [comment] 2017-12-02 20:55
I'm going to close this issue as it is over 6 months old. Feel free to re-open if you are still having this problem and want to continue investigating.

**Closed by ffulin** 2017-12-02 20:55 UTC
Labels: Need More Info (or Blocked), Question
