### ISSUE TITLE
Does changing a .bff file trigger a full rebuild?

### ISSUE THREAD

**Issue by Dragnalith** [fastbuild/fastbuild#412] opened 2018-04-14 04:12 UTC
I have read fastbuild code, and just to make sure I have well understood the node graph reloading:
If I am changing the bff file in anyway, it will kill the incremental build because behind it will discard the previous node graph database which also contain the timestamp and lastBuildTime of the previous build?
It seems to be what happen on my computer.

Isn't it an issue in real life production? Everytime you add a new file, or new library, or rename something you know you will have to rebuild everything.

**Comment by ffulin** [comment] 2018-04-14 19:13
Changes to the bff currently trigger a rebuild. This is a limitation of the current bff parsing and dependency engine, but will be addressed in a future version. The internals are slowly being refactored towards the end state needed to fix this. The issue is being tracked here: https://github.com/fastbuild/fastbuild/issues/108

In terms of impact, while this limitation is certainly annoying when creating your initial build configuration, it's not generally an issue during production because you don't need to list your files explicitly. You can have FASTBuild discover files to build automatically (based on directory paths and wildcards), so when you add, remove or rename files, they do not trigger any unnecessary rebuilding.  For the remaining operations (like adding new libraries, or changing the actual build configuration), these tend to not be that common.

Just to be clear, the intent is to fix this so it's never an issue :)  Until then, using the cache feature can be a way to significantly reduce the impact of this limitation (since objects will be pulled from the cache instead of rebuilt).

**Comment by ffulin** [comment] 2018-04-29 00:35
Closing as duplicate.

**Closed by ffulin** 2018-04-29 00:35 UTC
Labels: Question
