### ISSUE TITLE
Proposal: Remote Race

### ISSUE THREAD

**Issue by hillin** [fastbuild/fastbuild#277] opened 2017-08-29 02:50 UTC
FASTBuild has a *Local Race* feature which runs the same job as distributed to a remote worker, the first completed work will be accepted and the other will be discarded. It would be cool if there is also a *Remote Race*, so spare CPU cores of workers can be utilized to improve local jobs' build speed.

In fact, FASTBuild always prefer to build locally. If the local machine can handle all the jobs, nothing will be distributed to other workers. This is based on an assumption that it's always faster to build locally than to send the workload to a remote machine and build remotely. This is mostly true, except for sometimes local CPUs are occupied by other compute-intensive processes. A remote race thread could be very helpful in this kind of scenario.

In another word, it is just **changing FASTBuild's strategy to always distribute jobs to remote workers. If any local core is spare, a local race will also be spawned**.

I've made a rough test a while ago. A simple build, which is consisted of 8 jobs (3 preprocess, 3 obj, 1 lib and 1 exe) and normally take some 10 seconds to finish, spent 5'30'' while VAssistX is scanning my Unreal solution and occupied all the processors. We may cut off a half of this time if we have this mechanism implemented (but the proprocessing stage has to be done locally).

**Comment by ffulin** [comment] 2017-08-29 03:38
> In fact, FASTBuild always prefer to build locally.

It's a little more complex than that. FASTBuild will exhaust all work that can only be done locally first, and will only then consume local jobs. From this perspective, it tries to maximize the distributable work. You are right though that if there are enough local CPUs to compile all the jobs, then they can all be consumed locally before they get a chance to be distributed. I can see how from that perspective you might consider it to favor the local CPUs.

So the question is whether FASTBuild should try to send work to remote workers even after it has started that work locally. Certainly this is possible. Implementing that would require:
a) The core job management would to be changed. Given the highly non-deterministic and asynchronous nature of the network this is some of the scariest code to touch.
b) The "local race" actually has a dirty little secret, which is that one it starts it always uses the local job, even when the remote one finishes first. This is a limitation in the implementation that needs to be fixed. A prerequisite for fixing this is the ability to cancel local jobs (which was partly solved by the new experimental -fastcancel functionality (https://github.com/fastbuild/fastbuild/commit/28f47bec90ed06eeeb61e672efc991c4a2de5609))

The case you mention, of Visual Assist deciding the best time to scan all your local files is when you start a build, is really something that should be fixed in Visual Assist. (I have seen this behavior myself - the PC being completely idle until the moment you start compiling - it's as though the VA code has a bool around the wrong way :) It's one of the reasons I stopped using VA 4 years ago - I'm sad it still isn't fixed, though to be fair I didn't report it)

The functionality you propose could potentially improve your 5 minute build time as you say, but it would never be as good as fixing Visual Assist's bug (as you note some work still needs doing locally: preprocessing, linking etc).

The question then is whether it is worth complicating FASTBuild for the case where the local machine is already doing some unrelated work. I think there are better improvements that could be made to FASTBuild (like making the race a real race in all cases for example).

**Comment by hillin** [comment] 2017-08-29 04:08
Thanks. Actually I think I cannot blame VA, because it has already started its work at the time I started the build. It's not rare that VA needs to do a full scan to the entire solution of Unreal Engine, and the scan could take up to 30 minutes. Although I admit most of the scan are duplicated efforts, it's Unreal's mechanism that the solution file should be regenerated whenever a file is added or removed. So I think it's not the same issue you've encountered with VA several years ago.

So my idea here is, try to detect whether there are enough processor resources before starting a job locally (except for those has to be done locally). If not, dispatch it to a worker. Then the idea of race threads came into my mind, so I thought maybe it's more straightforward to try to distribute as many jobs as possible, keep local processors free and start races on them. I guess this wouldn't be a difficult thing after the "little dirty secret" of race threads is fixed, right?

**Comment by BrodyHiggerson** [comment] 2017-08-29 04:18
@hillin As another UE4 user, I'd like to quickly point two things out.

Firstly, when you add new files to a UE4 project, you don't _have_ to regenerate the solution - you can add them manually by dragging them into VS or using _Add->Existing Item..._ is the right-click context menu in your Solution Explorer. UE4 only cares about the files on-disk - the solution is generated for your convenience.

Secondly, take a look at the latest versions of Visual Assist - the latest release notes (General Release Build 2231) say;
> Initial parse of large solutions, especially those that include Unreal Engine 4 (UE4), requires less time. Initial parse times for UE4 have dropped by up to 75%.

Just thought I'd throw that out there! I'm not sure I agree with blaming VAX 100% - I'm sure there are other possibilities for local CPU usage outside of that, but not sure how common it is in regards to whether or not it's worth the changes to FASTBuild. I don't have the context required to say :)

**Comment by ffulin** [comment] 2017-08-29 04:24
> Actually I think I cannot blame VA, because it has already started its work at the time I started the build. 

That's fair :). I guess it would be nice if VA paused scanning if you start a build - perhaps that's a feature worth requesting?

> So my idea here is, try to detect whether there are enough processor resources before starting a job locally 

It could be possible to throttle the local CPUs based on CPU usage. That would mean it would simply take less local jobs, increasing the chance for distribution (scaled according to how much local load there was). I think that would give the result you are looking for with the bonus of not having to touch the core distribution or remote job management algorithm. That might even be a win even before the local race issue is fixed. The code for measuring local cpu usage (excluding yourself and child processes) already exists in the worker too. As long as we made sure it never throttled below 1 cpu locally this might not be too hard.

**Comment by hillin** [comment] 2017-08-29 04:43
@BrodyHiggerson Thanks for the suggestions!

Yes I'm aware that I can manually maintain the solution files, and I use this method all the time. The real pain is, I sometimes have to switch between branches in my work (i.e. one in 4.15, one in 4.16) and they are quite different in the file tree, so I have to regenerate the solution file after every branch checkout. I have to do this frequently, but not frequent enough for me to maintain two repositories locally (the repo is really huge, bad idea to use git with UE4, even with LFS). Anyway, this is something off-topic here :)

And I'll definitely check out the new VAX.

> I guess it would be nice if VA paused scanning if you start a build - perhaps that's a feature worth requesting?

@ffulin yes, sure I can open a ticket to the Whole Tomato guys. My point here is, there could always be some greedy programs occupying your computer from time to time, if not VA. And it would be sweet if I can retain more of my local process resources and use more of others', especially when your team has one or more dedicated build machines which has tens of cores and nothing to do.

**Comment by belkiss** [comment] 2017-08-29 20:36
Have you tried the new -forceremote command line argument? I get faster total build times when used.
It could probably even be made faster by skipping the .pch file generation, as they are only relevant for local builds.

**Comment by hillin** [comment] 2017-08-30 07:57
@belkiss where can I use that command line argument?

**Comment by belkiss** [comment] 2017-08-30 08:26
Just pass it to the command line when invoking FastBuild. It's been added at commit e03b3452d19b6f56f38b2bb5089ee3cacc33fcc4

**Comment by hillin** [comment] 2017-08-30 08:30
Oh I didn't know it. This could partially solve this issue, I think.

**Comment by Domain** [comment] 2017-09-01 02:20
@belkiss After using -forceremote, there is a long time no local build at all, more than 10 minutes. It's expected behavior? So the total build time almost double.

**Comment by ffulin** [comment] 2017-09-01 05:31
I consider -forceremote to be a debug option. Using it will typically result in slower builds (even if in some situations it could improve build times). More importantly though, it can result in a build that never completes! 

The [documentation in the dev branch](https://github.com/fastbuild/fastbuild/blob/dev/Code/Tools/FBuild/Documentation/docs/options.html) details this:

**Prevents all local compilation of distributable jobs.**

FASTBuild will normally utilize local CPU resources to compile distributable jobs in several
situations, in order to improve performance:
 * When there are no remote workers available (otherwise build would not complete)
 * When all remote workers are busy and local CPUs would be idle
 * When blocked on remote work

This option prevents local consumption of distributable jobs in all these cases. This will generally
result in slower builds and may even prevent the build completing entirely. As such, this options should
generally only be used for troubleshooting. Additionally, this option disabled use of the cache.

**NOTE:** This option can prevent builds from completing (if no workers are available for example).
**NOTE:** This option will generally degrade build performance.

**Comment by belkiss** [comment] 2017-09-01 06:14
I only suggested it as a test, indeed, the feature is not stable and only there for debug.
In most of my cases though, I get faster build times thanks to it, when it doesn't fail for one of the reasons mentioned above :)

**Comment by Domain** [comment] 2017-09-02 03:17
@ffulin Thanks for the explanation. I have a question confusing me: increasing the worker number doesn't decreasing the total build time. I once have 7 remote workers, and now I add 8 more workers, but the total build time doesn't shorter. From the graph in FASTBuild Dashboard, I see lots of timed out. What's timeout means?

**Comment by ffulin** [comment] 2017-09-02 19:03
@Domain - It is frequently the case that the local machine will be the bottleneck in a distributed build, so there is always a point where adding more machines will not improve the overall throughput of the build. A timeout means that the main build (fbuild.exe) didn't hear from the worker for a while. In v0.93, the timeouts were way too low, causing a lot of unnecessary disconnects. This has been fixed in the dev branch, and those fixes will be in the next version (v0.94)

@belkiss - It could be interesting to work out why it's faster in the cases you are seeing. Out of interest, are you using a version based on v0.93? Or are you using the "dev" version (containing the fixes mentioned above).

**Comment by belkiss** [comment] 2017-09-02 19:40
@ffulin Just tried again:

Rebuild, no cache:
`73>Time:`
`73> - Real       : 2m 56.006s`
`73> - Local CPU  : 26m 16.191s (9.0:1)`
`73> - Remote CPU : 23m 43.009s (8.1:1)`

Rebuild, no cache, with -forceremote:
`73>Time:`
`73> - Real       : 1m 41.516s`
`73> - Local CPU  : 6m 7.376s (3.6:1) `
`73> - Remote CPU : 32m 42.890s (19.3:1)`

I run a custom version close to the dev branch. I have the fixes you mentioned, but I've seen this behavior since I implemented forceremote locally, around last year. It has no change that could explain that big a difference though.

**Comment by ffulin** [comment] 2017-09-02 20:05
@belkiss - Interesting - I wonder if it's the "race" behaviour. At the moment, that isn't a real race, so potentially it could make things worse in some cases (which is something I'm closer to being able to fix now that -fastcancel is supported). I wonder if looking at the timeline of the two builds would highlight anything interesting.

**Comment by ffulin** [comment] 2017-12-30 18:25
I've just implemented proper races, so if a remote job completes after we start the local race, FASTBuild will now abort the local job and take the remote result. Since the race could start just before the remote job would have finished, the saving can be as much as the entire cost of the object. If the object in question in a Unity/Blob file, this can be significant.

This change (https://github.com/fastbuild/fastbuild/commit/da72ebaf27eadfaba31d634d14cbe47b7698b89b) should be in the next version (v0.95)

**Comment by ffulin** [comment] 2018-02-17 23:41
v0.95 has been release, with true race support (either local or remote machine can "win"). I think that resolved the original question this issue was about. We can create new issues if any followup is needed for any other things talked about in this thread.

**Closed by ffulin** 2018-02-17 23:41 UTC
Labels: Question
