### ISSUE TITLE
Crash when using distributed build 

### ISSUE THREAD

**Issue by neo2buha** [fastbuild/fastbuild#310] opened 2017-10-22 14:07 UTC
Hi 
I have a crash when running fastbuild using -dist 
without dist it doesn't crash

Unhandled exception at 0x00007FF82B4C60DE (rpcrt4.dll) in FBuild.exe: 0xC0000005: Access violation reading location 0x00007FF825A98000.

The crash happens on a worker thread when the application closes.

The callstack is not particularly helpful. 
 
>	rpcrt4.dll!00007ff82b4c60de()	Unknown	Non-user code. Cannot find or open the PDB file.
 	rpcrt4.dll!00007ff82b4da348()	Unknown	Non-user code. Cannot find or open the PDB file.
 	rpcrt4.dll!00007ff82b4d92ec()	Unknown	Non-user code. Cannot find or open the PDB file.
 	00007ff825a6223c()	Unknown	Non-user code
Even though I select microsoft symbols server it doesn't seem to find any symbols for it 

the main thread is waiting in the destruction of a client class 
 	[Inline Frame] FBuild.exe!Thread::Sleep(int) Line 110	C++	Symbols loaded.
>	FBuild.exe!Client::~Client() Line 65	C++	Symbols loaded.
 	FBuild.exe!Client::`scalar deleting destructor'(unsigned int)	C++	Non-user code. Symbols loaded.
 	FBuild.exe!FBuild::Build(Node * nodeToBuild) Line 429	C++	Symbols loaded.
 	FBuild.exe!FBuild::Build(const Array<AString> & targets) Line 293	C++	Symbols loaded.
 	FBuild.exe!Main(int argc, char * * argv) Line 533	C++	Symbols loaded.

One thread is closing a handle 

>	[Inline Frame] FBuild.exe!Thread::CloseHandle(void *) Line 238	C++	Symbols loaded.
 	FBuild.exe!Network::GetHostIPFromName(const AString & hostName, unsigned int) Line 104	C++	Symbols loaded.
 	[Inline Frame] FBuild.exe!TCPConnectionPool::Connect(const AString &) Line 200	C++	Symbols loaded.
 	FBuild.exe!Client::LookForWorkers() Line 219	C++	Symbols loaded.
 	FBuild.exe!Client::ThreadFunc() Line 127	C++	Symbols loaded.
 	FBuild.exe!Client::ThreadFuncStatic(void * param) Line 112	C++	Symbols loaded.

and the rest of the threads are waiting 
>	[Inline Frame] FBuild.exe!Semaphore::Wait(unsigned int) Line 99	C++	Symbols loaded.
 	[Inline Frame] FBuild.exe!JobQueue::WorkerThreadWait(unsigned int) Line 529	C++	Symbols loaded.
 	FBuild.exe!WorkerThread::Main() Line 126	C++	Symbols loaded.
 	FBuild.exe!WorkerThread::ThreadWrapperFunc(void * param) Line 112	C++	Symbols loaded.

This rarely happens in debug but it happens most of the times in release ! 
Let me know if you have any thoughts on how to debug this !

**Comment by ffulin** [comment] 2017-10-24 04:29
Thanks for reporting the bug. This is not something I've ever seen, and likewise something nobody else has reported. If you have a reproducible case, I'd love for us to try and work out what the problem is.

Firstly, I see you are using the Windows x64 version - can you please confirm which version of FASTBuild you are using?

Assuming it's latest (v0.94 at time of writing) I can think of two possible avenues to progress:
a) You can send me a crash dump, I may be able to sanity check some more things about the internal state of fbuild.exe. You can send a debug mini dump via the contact info on the website (http://fastbuild.org/docs/contact.html) to avoid posting it publicly. Of course I understand if you are not able to/are not permitted to do that due to issues with sensitivity of your project.
b) If you run the debug build from within the debugger, and manage to repro the crash, you should have thread names available. With this we can potentially determine if the thread the crash is in is owned by FASTBuild, or if it's a Windows system thread.

Failing that, if the release build reproduces for you reliably, we might need to have you build and modify your own release build to so we can try to log some additional information about what (I presume) is being used after free.

**Comment by ffulin** [comment] 2017-12-03 03:04
I managed to reproduce and fix this crash. It could also manifest as deadlock in some situations. The fix (https://github.com/fastbuild/fastbuild/commit/74b4a6af3d2fb777de7e47de9eb8604898fc11b3) will be in the next release (v0.95). I'll leave this issue open until that version is released.

Thanks for reporting this and your help tracking it down!

**Comment by ffulin** [comment] 2018-02-04 21:20
v0.95 has now been released and includes the fix mentioned above for this crash. Thanks again for reporting this issue!

**Closed by ffulin** 2018-02-04 21:20 UTC
Labels: Bug, In Next Version
