### ISSUE TITLE
How does FastBuild determine what data can be read from the cache?

### ISSUE THREAD

**Issue by jackknobel** [fastbuild/fastbuild#245] opened 2017-05-16 08:33 UTC
Sorry for placing this kind of question here let me know if there is more of an appropriate place.

I am slightly confused as to how FastBuild determines what can be read from the cache and what cannot.

I am running a build of UE4 using the implementation found here https://github.com/liamkf/Unreal_FASTBuild (slightly modified to support VS17 which can be found here: https://github.com/liamkf/Unreal_FASTBuild/pull/17) and I am getting some percuiliar results.

Caching only appears to be per machine, that is to say it doesn't use other machines previously compiled results only the previous results that they themselves have generated.

My current setup is I have a build machine that automatically compiles when a new changelist is submitted, this machine is set too read/write. All other pc's on the network are set too readonly. 

The expected result would be that the other PC's on the network can read from the central build server cache to speed up their results. Alas they cannot but they CAN however read from the cache if they are set to read/write and have previous results written to the cache.

Now I am thinking this maybe a problem with the implementation of FastBuild in Unreal, a problem with VS17 or actually how Unreal generates the files. Either way I am hopeful that with the information you can provide I can dive deep into the problem and fix it!

Thanks heaps,
Jack

**Comment by ClxS** [comment] 2017-05-16 09:02
Hi @jackknobel ,
You'll need to do a bit of debugging here. Around line 956 in your version, add -verbose and -j0 to the FBCommand line and run the build on two different machines. This'll display cache hashes results in a aaa_bbb_ccc_ddd, where:
- **a** is the hash of the preprocessed source
- **b** is the hash of the command line arguments
- **c** is the hash of the toolchain
- and **d** is the PCH 'key'

A mismatch in **c** means you're using different versions of the compiler on different machines - a problem we had before was mismatching VS patch versions.

A mismatch in **a** means that either you have your source in a different path across different machines which isn't yet supported by fbuild. Another issue we had causing mismatches in **a** was a different Windows SDK being used on different machines.

**Comment by jackknobel** [comment] 2017-05-16 09:13
Brilliant thanks @ClxS; I will look into that!

How specific do the VS versions need to be? The reason I ask is VS17 has been getting minor patches quite frequently and that could be quite difficult to keep a consistent cache.

Which leads me into another question, does the cache get cleared after a certain ammount of builds or time? Keeping a steady VS update schedule is manageable but having endless disk space is not haha

**Comment by ClxS** [comment] 2017-05-16 09:18
In our experience it needed to be the exact same VS minor patch, otherwise we'd get mismatches still. I don't have anything to do with managing that so I've no advice there. :(

There isn't any built in cache management/clearing.
It looks like your implementation might have a flaw with how you set the CacheMode. I'd recommend making DefaultCacheMode = ReadOnly, and setting it to ReadWrite when using the build machine. That'll help you control the cache size since then only the checked-in machine-build built files will be added to the cache.

**Comment by jackknobel** [comment] 2017-05-16 09:23
Hmm interesting, that could be a minor problem. But at least addressable!

In house it's set to readonly I just left it as ReadWrite to not affect any other developers using the implementation when it got merged 😄

**Comment by jackknobel** [comment] 2017-05-17 06:01
Okay so if what you said earlier is correct it appears the discrepency is in A and B (preprocessed source and the command line arguments) whereas C and D are matching.

The commandline arguments I semi understand as locally I build through VS however with the build server I trigger the builds through a [BuildGraph](https://docs.unrealengine.com/latest/INT/Programming/Development/BuildGraph/) script.

Why would the preprocessed source be any different? I read [here](https://github.com/fastbuild/fastbuild/issues/179#issuecomment-268305640) you have to have an identical directory structure. Could that be the cause of the problem?

**Comment by ffulin** [comment] 2017-05-19 06:31
I'll try to answer all the questions below. Let me know if I missed something, or if you want further clarification on anything.

**Compiler Binaries**
The compiler must be a binary identical match. This is to ensure you get the same results when you get a cache hit as if you compiled locally. If FASTBuild retrieved versions built by an older compiler, it might return bad code if an old compiler version had code gen bugs - if you locally and still got the bad code, that would be very confusing/dangerous.

To keep the exact same version on all machines (users and build machines), I recommend checking the binaries into your source control and considering them part of what you need to sync to build. It fixes the problem of keeping everyone on the correct version, avoids people wasting time chasing bugs fixed in newer compiler versions because they didn't read the "update your compiler email" and also makes managing your build machines nice and easy.

For similar reasons, I recommend checking in all 3rd party libraries and SDKs into your source control as well.

**Cache maintenance**
There is no automatic cache maintenance. You will need to periodically schedule a job to purge or trim your cache. I hope to add a -cachetrim or similar command line to a future version of FASTBuild to help with this.

**Preprocessed Source**
The preprocessed source generally contains full paths to files. This feeds into both debug info and __FILE__ directives. Naturally this means you have to have matching absolute code paths in order for caching to work.

**Cache modes**
Having your build machines populate the cache, and developers work in read only mode is the recommended setup. If your CI system builds quickly (which hopefully FASTBuild helps it to do) then the cache will be well populated. Read-only cache mode is slightly faster for developers as it avoids some of the cache overhead.

**Comment by jackknobel** [comment] 2017-05-19 06:58
Thanks for the info @ffulin! 

Compiler binaries are shared for 3rd party libraries and SDK's however engine and project dll's are not (as the developer locally compiles them). This may change if it is the preferred workflow for FastBuild.

Does it compare the full folder structure like so
> C:\Workspace\Blurg\Project\Code

vs

> D:\MyFirstProject\Developer\Project\Code

or does it use a relative path for the caching (So just the Project\Code) folder etc.

If it does use absolute is there anyway to have the caching consider the relative Preprocessed Paths instead of absolute? That way we don't have to rely on developers to keep their paths the exact same to reap the full benefits of FastBuild?

Do appologise if I am not understanding correctly! 

Once again thanks for the info 😄

**Comment by ClxS** [comment] 2017-05-20 10:43
@jackknobel It will use the full, absolute path. This isn't something directly caused by FASTBuild, but is due to the pre-processing which writes all includes as their absolute paths.

The approach we take on our project is to create a drive which maps to our workspace (subst), and open our project through that. So, D:/ClxS/Perforce would be mapped to Z:/. Every developer would be using Z:/ as their working directory, allowing cache hits.

**Comment by ffulin** [comment] 2017-05-28 16:59
@jackknobel I wouldn't expect you to share your engine or project dlls via source control if you are building them locally - FASTBuild doesn't benefit from that. The use of source control Isuggested is just recommended as a way to keep third party libraries and your toolchain at the exact right version across all users. If you have an alternative mechanism for managing that (technology or process), it will work fine without checking any of it into source control.

Assuming everyone has the same versions, then you are left with the issue of standardized paths. I usually suggest all developers standardize their mappings to the same path - it's a one-time hassle, but keeps everything simple from that point onwards. We have a setup script that takes care of making sure everything is correctly configured for a user to have the cache work, and checking the paths is one thing it does. If you can't (or don't want to) do is this way, using something like @ClxS 's drive mapping is another good solution.

**Comment by ffulin** [comment] 2017-09-30 16:12
I'm going to close this issue as it seems the question(s) have been answered. Feel free to re-open if more info is needed.

**Closed by ffulin** 2017-09-30 16:12 UTC
Labels: Question
