### ISSUE TITLE
removing a .cpp from a DirectoryListNode does not cause a rebuild

### ISSUE THREAD

**Issue by lucasmeijer** [fastbuild/fastbuild#107] opened 2016-06-28 12:38 UTC
The DirectoryListNode.DoBuild() does get called, and it actually searches the filesystem, however the ExeNode does not realize that the there's one fewer ObjectNode to link, and thinks everything is just dandy,  instead of relinking without the objectfile belonging to the removed cpp file.

**Comment by ffulin** [comment] 2016-06-29 04:42
Hello

I've reproduced this bug. The linking will be correctly performed (i.e. no stale objects are ever used) if something else causes it to trigger, but if the only action taken is to delete a cpp file, it indeed doesn't trigger a re-link as it should.

It's almost hard to believe it took this long for this bug to be reported, but it's because most users use Unity to accelerate compilation, in which case deleting a cpp file causes a change in at least one unity cpp file and therefore rebuilds/relinks.

Thanks for reporting it!  I'll look into creating a fix.

**Comment by lucasmeijer** [comment] 2016-06-29 20:36
no worries, I'm not blocked by this, so if you don't need a fix, don't make one for me, just reporting what I found :)

**Comment by ffulin** [comment] 2016-06-30 02:40
It's definitely a bug that needs fixing. I'll keep this report open until it's resolved.  Thanks again :)

**Comment by ffulin** [comment] 2019-11-24 02:12
This dependency graph has been changed in a way that fixes this issue: https://github.com/fastbuild/fastbuild/commit/735ba92dfa2d37f0d53dce285a120af091903808). This fix will be in thenext release (v1.00). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment] 2020-05-04 01:47
v1.00 has now been released. It includes the overhauled dependency engine which fixes this issue (and others).

**Closed by ffulin** 2020-05-04 01:47 UTC
Labels: Bug, Resolved In Next Version
