### ISSUE TITLE
Regression in BFF parsing - string variables in #include parameter not expanded anymore

### ISSUE THREAD

**Issue by lucianm** [fastbuild/fastbuild#705] opened 2020-02-26 14:39 UTC
It seems that since the last release, a lot has been going on in `Code/Tools/FBuild/FBuildCore/BFF/BFFParser.cpp`, at least that's the area I'm suspecting this problem comes from.

We'we been trying to reuse a lot of complex BFF syntax by making use of loops and #include some BFFs either multiple times after altering some variables, or from different paths encoded with such a variable, like in this no longer working case I'm presenting here. Something is broken, and for reproducing, please try this minimalistic example [variable_expansion.zip](https://github.com/fastbuild/fastbuild/files/4256202/variable_expansion.zip) with the last released version and the current development build.
I'm listing the 4 files here also, they're all in the ZIP:

- _fbuild.bff_:
```
.BlaVar = 'Bla'
#include "fbtest_included.bff"

.BlaVar = 'Blu'
#include "fbtest_included.bff"
```

- _fbtest_included.bff_:
```
Print ('About to include fbtest_2beincluded_$BlaVar$.bff ...')
#include "fbtest_2beincluded_$BlaVar$.bff"
```

- _fbtest_2beincluded_Bla.bff_ and _fbtest_2beincluded_Blu.bff_ both contain just `Print ('$BlaVar$ was included')`

When running `FBuild.exe -showtargets` for example, this is the expected output, obtained with the last released FASTBuild 0.99:
```
FBuild.exe -showtargets
About to include fbtest_2beincluded_Bla.bff ...
Bla was included
About to include fbtest_2beincluded_Blu.bff ...
Blu was included
FBuild: List of available targets
```

With the current development version instead, this happens:
```
FBuild.exe -showtargets
Y:\fbtest_included.bff(2,10): FASTBuild Error #1032 - Unable to open include 'Y:\fbtest_2beincluded_$BlaVar$.bff'.
#include "fbtest_2beincluded_$BlaVar$.bff"
         ^
         \--here
```

**Comment by lucianm** [comment] 2020-02-26 14:42
Oh silly me, this has been already reported in #687  :-(

**Comment by ffulin** [comment] 2020-02-27 04:53
Indeed, this is a deliberate, though unfortunate breaking change.

Being able to reference variables during preprocessing was unsustainable and in many cases confusing and unintuitive.

The other issue you've discovered contains some information about alternative ways to manage cases that were a common use of this (including a list of things). Other cases, like setting some "parameters" before including a bff to re-use it still works as before.

If you have a particularly problematic use-case, let me know and we can see if there is a good alternative way to handle it.

**Comment by missmah** [comment] 2020-02-27 07:33
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} This will break the foundations of our build system which we've built up over 4 years... thousands of lines of BFF code in hundreds of files which are dependent upon this at the core.Unless the ability to conditionally include inside an If() is being added, I don't immediately see how we'll be able to support our build system on the next version.It's possible that an extensive rewrite, handling all of the cases we currently handle using a fork and join kind of style with variable includes instead within one uber file with If() branches everywhere might be able to produce similar behavior... But that sounds like a ton of painful work we don't have time for at the moment.This worries me :/ I hope I'm missing something and the solution isn't that dramatic - also this seems like the kind of change we'd want to throw a compiler warning about a version or two before breaking (Just my $0.02 there).                                                                                                                                                                          From: notifications@github.comSent: February 26, 2020 11:53 PMTo: fastbuild@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: Re: [fastbuild/fastbuild] Regression in BFF parsing - string variables in #include parameter not expanded anymore (#705)  Indeed, this is a deliberate, though unfortunate breaking change.
Being able to reference variables during preprocessing was unsustainable and in many cases confusing and unintuitive.
The other issue you've discovered contains some information about alternative ways to manage cases that were a common use of this (including a list of things). Other cases, like setting some "parameters" before including a bff to re-use it still works as before.
If you have a particularly problematic use-case, let me know and we can see if there is a good alternative way to handle it.

**Comment by ffulin** [comment] 2020-02-28 02:52
> Unless the ability to conditionally include inside an If() is being added,

@missmah. If() statements containing #includes work as before, as do #includes within #if directives. The exact order of operations is subtly different, but the end result (for usual cases at least) is the same.

The change that has been made is that all preprocessing is done in one pass before "executing" the bff script. This mirrors the behaviour of C/C++ etc. While the #include will essentially be unconditional, it won't be executed if the If() does not evaluate to true.

Additionally, you can still include files in loops and paramaterize them, using them as a poor-man's "function". While the include is "included" once instead of for every iteration of the loop, the contents is still evaluated for each iteration as before.

To summarize, the important behavioral changes are:
a) $ substitutions inside #include statements are no longer supported

The main use case I know of for this was defining an Array and then including files based on that list. To handle this case, you must now include the files directly instead. If the list was only used for the includes, it's a 1:1 replacement. If the list was additionally used for other things, you can avoid duplication between the includes and the list by having each included bff add itself to the list.

This is an annoying change, and one I had to deal with myself. If this impacts you, I hope the update for this is manageable.

b) all preprocessing is done in one pass inside loops, whereas it used to be done for every pass of the loop

As noted above, the evaluation of the included content is as before.

The difference is that you could use #define to control subsequent iterations of the loop. I don't know of any desirable usage of this behavior, and the behavior was very unintuitive.
---

If you have use cases that are particularly problematic, or think these changes might be problematic in a way I'm not aware of, I'd be happy to help try and find alternative patterns to solve those use cases.

**Comment by mkujawa** [comment] 2020-03-12 17:08
We were using variables in includes for polymorphism

```
.ProjectType = "Application"
#include "DoProjectSetup.bff"
```

DoProjectSetup.bff:
```
...
#include "SetupIncludes_$ProjectType$.bff"
...
```

Since bff doesn't allow user-defined functions, `#include` is as close as we get.  We'll now need to make dispatcher bffs that are giant case statements to mimic the old polymorphic behavior, which is definitely not as elegant, and probably considerably more resource intensive.
(This is also why I found it difficult to know what variables were in scope, prompting my MR for printing all variables.  It's impossible to know from looking at a bff what context it's been included from, and thus what variables are in the parent scope.)

**Comment by ffulin** [comment] 2020-03-13 05:48
@mkujawa Thanks for the info about your use-case.

> Since bff doesn't allow user-defined functions, #include is as close as we get.

The irony here is that the refactoring that removes support for variables inside include directives is a step towards being able to add exactly that (user defined functions). The bff parsing is much simpler now, more easily extensible and over twice as fast all of which allow progress to be made on some of these much needed features.

Now we just need to manage the transition.

> We'll now need to make dispatcher bffs 

I guess you mean something like this:
```
If( .ProjectType == .ProjectTypeA )
{
    #include "SetupIncludes_ProjectTypeA.bff"
}
...
```
which could work well, but might have some variable scope challenges.

Or perhaps (with accompanying changes to the invocation), something like this:
```
#if PROJECT_TYPE_TYPEA
     #include "SetupIncludes_ProjectTypeA.bff"
#endif
...
```

Neither of those is great, but perhaps they could do the job? I'm open to other suggestions for other things that might make this transition easier.

> I found it difficult to know what variables were in scope, prompting my MR for printing all variables.

I like the idea behind the PR, and I understand the problem it solves. My primary concern with the PR stems from the custom syntax for controlling the print behavior. I'd like to try and find a way to move that PR forward.

**Comment by eclazi** [comment] 2020-04-15 15:07
We were using this do define custom worker lists.

```
; User can optionally create a environment variable pointing at a bff file which contains their own worker list
#if exists(FASTBUILD_WORKERS_LIST)
    #import FASTBUILD_WORKERS_LIST
    #include "$FASTBUILD_WORKERS_LIST$" ; file should be a bff file defining .WorkersList
#else
    #include "workers-default.bff"
#endif

...

Settings
{
   ...
   .Workers=.WorkersList
   ...
}
```

**Comment by ffulin** [comment] 2020-04-16 01:27
**@eclazi > We were using this to define custom worker lists.**

There are 2 features in v1.00 which might serve as alternatives:

**a) New FASTBUILD_WORKERS environment variable.** Allows a colon delimited list of workers to be configured. If you embed the list directly in the env var, this could be used.
**b) New #if file_exists("File.bff")** Allows detection of optional files which can be included if present. If you standardize the name of the file this could be used.

Do either of those work as a suitable replacement?

**Comment by ffulin** [comment] 2020-04-23 02:59
User Functions have been added (https://github.com/fastbuild/fastbuild/commit/bdbad09abeb99fb1070d13fe7296f42fe052f2a5) and will be in the next release (v1.00)

Functions can be defined and invoked when needed to reduce duplication in configs and to avoid the need to use #include as a poor-man's function call. This isn't a direct replacement for the removed functionality (injection of variables into #include paths) but should prove to be a powerful tool for solving configuration duplication problems.

**Comment by ffulin** [comment] 2020-05-04 01:54
FASTBuild v1.00 has been released. This version includes some new features as mentioned above, which should make the breaking changes less painful.

If new problematic use-cases come to light (and I suspect they will) I think we should create new issues to address/track those. With that in mind, I'm going to close this issue.

**Closed by ffulin** 2020-05-04 01:54 UTC
Labels: Question

**Comment by missmah** [comment] 2020-12-29 01:52
I was just about to finally go implement the "big switch statement" @mkujawa spoke about above so we could finally update to the latest `fastbuild`. Unfortunately, I just realized that there's a much more basic and pervasive use of this feature which we *cannot just workaround* which basically means we must fork fastbuild and will never be able to take up anything past `v1.0`. This is pretty depressing.

We have built a module system (similar to `npm`) on top of `fastbuild`. It's pretty neat.

The extensiblility @mkujawa talked about above was something I was disappointed about losing, because it means now we need to have a bunch of boilerplate added and updated centrally to support new project types; but, it's a compromise that we can make due with.

What I absolutely don't want to make due without is dependent includes.

We include optional user-specified `.bff` files for configuration options.

For example, the meta-project `3rdparty.bff` has a bunch of sub-projects, each one will have files named things like `$MetaProjectName$.$ProjectName$.ExtraOptions.bff` which get included by the system. But users can optionally do neat things like specify to include the default extra options file, or share extra options files between sub-projects, etc.

An example of shared sub-project extra configuration might be 5 sub-projects (out of say `10`) sharing `SharedTools.ExtraConfiguration.bff`

Moreover, these files don't simply get included by the user's code. *They get `#included` by special package manager code during inner-loops over the configuration setup for the projects.* So each project is actually setting a `.ProjectExtraConfigurationFile = 'SomeString'` and the `#include` is using a bunch of path variables `/$ProjectExtraConfigurationFile$`

This literally isn't something we can just replace by having the user's code hard-code the names of the files to include. *We have to construct absolute paths using variables* from within that central *package manager inner-loop code* to `#include` files from within the *package's path*. I don't think there's any way to do this with `fastbuild 1.0+`

I understand why you made this breaking change. Here I ask is there any possible way to add a dependent include feature back into the language? Without this, there's no way we can upgrade to `fastbuild 1.0`, and we'll end up having to live on a forked version forever. :(

**Comment by ffulin** [comment] 2021-01-05 08:38
I've been giving this some thought over the last few days to try and figure out a way to support your use-case.

I'll add some more context here and then propose a not fully formed idea.

Please let me know what you think.

----

**Some more background**

The reasons for the change are reasonably well understood I think (maintainability, performance and intuitiveness), but I can't understate just how unintuitive the old behavior was. For example:
```C++
ForEach( .Thing in .Things )
{
      ...
      #include "Blah.bff"   <<--- This could be impacted by SOME_MACRO in every loop after the first
      ...
      #define SOME_MACRO
}
```
No sane person would deliberately rely on that, but you could have something like this by accident. That could create some very surprising and hard to debug problems. That it looks just like C/C++ but doesn't behave at-all like C/C++ was a huge problem and a very poor early design choice on my part.

----

**Support for the old behavior behind a toggle**

The old behavior, while convenient in a few ways, was conceptually bad as noted above, but putting that aside, supporting *both* old and new parsers is unworkable in my opinion:
 - All the maintenance problems of the old code *on top of* the new code
 - Loss of many new features/syntax enhancements added in the last several versions (or the need to backport them all)
 - Tests would have to be re-written to run for both parsers and two sets maintained in some cases where they diverge
 - All the bugs fixed by the new parser would be re-introduced (and would need to be back ported)
 - All future improvements would have to be written twice

If you took that maintenance on entirely yourself, I think you'd quickly end up where you are now - not being able to update because all changes would have to be back ported.

----

**How do we resolve your use-case**

I think to find a way forward, we need to come up with a *new* behavior that solves for this use-case rather than trying to add back the old behavior.

I'm open to entirely new constructs or syntax to solve this problem. If we can come up with a good solution, I'll implement it.

With this in mind, I've been trying to brainstorm a way to provide what is essentially the old behavior, while trying to avoid the problems that came with it.

What I have so far is:
```C++
ForEach( .Package in .PackageManager_PackageList )
{
	Invoke( '$PACKAGE_MANAGER_PACKAGE_ROOT$/$Package$/$Package$.bff' )
}
```
(where "Invoke" is just a placeholder name)

If each Invocation was self-contained wrt parsing (i.e. there would be no passing of macros into the invoked file), I think this might be workable. I think this would avoid *most* of the confusion around the behavior of preprocessing vs evaluating the config as well as avoiding the need to maintain two code paths.

I'm cautiously optimistic that this (or something adjacent to it) might be a workable solution, but I do have a fear there is a lurking problem since it is still mixing the two worlds of "parsing" vs "evaluating". My hope is that by being a new explicit and well defined construct, the problems might be avoidable and the tradeoffs acceptable.

I think I'd need to do a spike to work out if this makes sense.

I'd appreciate your thoughts on how this might work (or not) for your use-case.

**Comment by lucianm** [comment] 2021-01-06 16:02
@missmah: No, I'm not maintaining a fork after losing this variable expansion feature in the parser. For our use case, migrating the compact construct of dependably #include-ing some BFF only required us to explicitly #include them 13 times, everything in the same BFF so it wasn't a big deal for us, fortunately. Seems like at your side things look a great deal different, I pity you.

At the same time, I also hope @ffulin is able to come up with some reasonable , useful alternative which would help you but also wouldn't make code maintenance difficult again in that area, keeping FASTBuild moving in forward direction ;)

**Comment by missmah** [comment] 2021-01-08 20:15
> **Some more background**
> 
> The reasons for the change are reasonably well understood I think (maintainability, performance and intuitiveness), but I can't understate just how unintuitive the old behavior was. For example:
> 
> ```c++
> ForEach( .Thing in .Things )
> {
>       ...
>       #include "Blah.bff"   <<--- This could be impacted by SOME_MACRO in every loop after the first
>       ...
>       #define SOME_MACRO
> }
> ```
> 
> No sane person would deliberately rely on that, but you could have something like this by accident. That could create some very surprising and hard to debug problems. That it looks just like C/C++ but doesn't behave at-all like C/C++ was a huge problem and a very poor early design choice on my part.

Ironically, I deliberately relied on exactly that behavior. I'm not sure why you say no sane person would deliberately rely on that, besides that it differs so much from conventions of e.g. `C/C++`

------------------------------------------------------------------------------------------------------------------------------------------

The authors of C++ templates built them with this use-case in mind:
```
template< typename T >
struct MyContainer
{
  T      *m_pArrayOfT;
  size_t m_szArraySizeInElements;
}
```

And then they were used for things like this:
```
template< typename T >
struct MetaFunction
{
    typedef typename T result_type;
}
```

I'm sure the original authors of C++ templates never envisioned the crazy Turing-complete things that would be built on top of the above construct; but, there were many reasons why people did so (some crazy/stupid, many quite useful)!

------------------------------------------------------------------------------------------------------------------------------------------

Anyway, back to the discussion at hand, I have some initial feedback/proposals, but I'd also like to take some more time to think things through more fully and return with more comments on this proposal.

# 1. I think the BFF parser will need to add support for #define MACRO SomeStringValueHere
* Which also likely means all the CAT AND XCAT macro madness that C ends up with for concatenating strings at pre-process time.
* This way you could do:
  ```
#define THIS_PACKAGE_NAME PluginCore
.PackageName = STRINGIFY( THIS_PACKAGE_NAME )
#define THIS_PACKAGE_BFF_INCLUDE IVR_CONCATENATE_PACKAGE_INCLUDE_PATH( BASE_BFF_INCLUDE_ROOT, THIS_PACKAGE_NAME )
#include THIS_PACKAGE_BFF_INCLUDE
```

This would solve the dependent include problem in the same way that `C/C++` solve it via the macro system. It comes with all the inelegant warts of using the macro system like that, but has the same level of expressiveness as C/C++, and while it's syntactically lost a lot of sugar compared to the single-pass BFF parser, the dependent-include concept can still be implemented.

# 2. I think some solution for dynamic inheritance will be necessary.
Past the general "dependent-include" problem above, where we are dynamically concatenating/generating the dependent filenames to `#include` during parsing, which again can be solved the same way `C/C++` solve it with macros, we were also using this `#include "$Variable"` syntax/behavior for implementing something akin to `poor-person's virtual inheritance/dynamic dispatch`. As mentioned above, for the simpler cases, we can just implement big switch statements manually to cover most of the use-cases for this. I need to do more thinking and looking into how we were using it to see if all of our remaining use-cases could be manually expanded by-hand if we had the dependent-includes macro expansion mentioned above (or not).

# 3. The "crazy" `PrintTextFile()` "solution" I mentioned in my previous post above does _seem to work_ - the biggest issue I see there is that it serializes parsing, which might prevent a parallel parser implementation in the future (though, if you made a first-class syntax for this that used `PrintTextFile()` and `#include` behind the scenes, you could do something like rename the temporary files to include `_THREADID` in the path/filename, such that each parsing thread could have its own scratch space. You could also probably do an in-memory implementation that didn't actually require using files-on-disk at all.) Maybe this is what you were thinking of doing for the `Invoke()` syntax? If so, I'm not sure why `Invoke()` wouldn't be able to receive macros from the parent scope? If `Invoke()` could receive/modify macros in the parent scope as the current parser does, I think this would likely be a workable solution...
* I have the feeling that maybe I'm not accounting for some change with the 2-pass parser here, though, which would break the `PrintTextFile --> #include` prototype that I built?
