### ISSUE TITLE
Empty array type and concatenation error

### ISSUE THREAD

**Issue by poppolopoppo** [fastbuild/fastbuild#15] opened 2015-06-26 10:56 UTC
I came across an error with this snippet :
````
.UntypedArray = {}
.Struct = []
.ArrayOfStructs = { .Struct }
.UntypedArray + .ArrayOfStructs
````
Which generates :
**fbuild.bff(4,10): FASTBuild Error #1034 - Operation not supported: 'ArrayOfStrings' + 'ArrayOfStructs'.**

Empty arrays seem to be typed by default as arrays of string when declared with {}, which later causes a typing error when I try to concatenate it with an array of structs.

**Comment by ffulin** [comment] 2015-06-28 00:07
Yeah, for historical reasons, empty arrays are considered to be of type ArrayOfString. There is no concept of typeless variables, let alone arrays.

There are three posibilities:
**a) Allow the type to change if assigning to an empty array.** I'm worried that this might break something.
**b) Make empty arrays typeless.** This would require checking lots of places to see how the code would cope with that. The result would be clean, but it's a non-trivial amount of work.
**c) Add a way to declare an empty ArrayOfStruct.**  This is the safest option, but I don't have a good idea what the syntax should look like. It would probably need to be some weird special case like this:
.ArrayOfStructs = { [] }
Doable, but a bit magic and not at all intuitive.
If there was a good syntax for this, it might be ok.

**Comment by poppolopoppo** [comment] 2015-07-04 11:21
* **c)** the `{ [] }` syntax would prevent handling inline definition of structs in an array like this :
````
.ArrayOfStructs = 
{
    [
        .Name = 'a'
    ],
    [
        .Name = 'b'
    ],
}
````
This would make `{ [] }` confusing between _an empty array of structs_ or _an array containing one empty struct_. Ruby has [alternate perl-like array declarations](https://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Literals#The_.25_Notation) like `%w[]`, something like that would be doable. But still I find it  a bit weird having a special syntax for that.
* **b)** is clearly the cleanest, but as you said it is not trivial and very risky.
* **a)** should do the trick for a very small amount of work without excluding b) in the future. The problem is that instead of a) & b) it won't fix this problem :
````
VCXProject( 'proj' )
{
   .ProjectConfigs = {}
}
````
````
FASTBuild Error #1050 - VCXProject() - Property '.ProjectConfigs' must be of type <ArrayOfStructs> (found <ArrayOfStrings>)
````

**Comment by ffulin** [comment] 2015-07-04 16:09
You're right about c) - this could be nice to support in the future:
```C++
.ArrayOfStructs = 
{
    [
        .Name = 'a'
    ],
    ....
```

I'm thinking maybe some (optional) more explicit variable declaration syntax could help. A few options below. We'd need to chose very carefully to avoid pitfalls like you caught above.

```C++
(ArrayOfStructs).X = {}
```
or:
```C++
.X = (ArrayOfStructs){}
```

It doesn't feel as elegant as I would like, but something along those lines might do the trick.

**Comment by poppolopoppo** [comment] 2015-07-11 12:46
This alternative syntax is annoying me, I am still searching for a better solution... but **b)** might be the only right answer. 

Maybe I'll give it a try by adding a new variable type for empty arrays.

**Comment by ffulin** [comment] 2015-07-12 01:33
I'm thinking about a few options that could complement the existing syntax (i.e. all existing stuff would work out type by default, but we could allow it to b set explicitly.

How about:
```C++
arrayOfStruct .MyArrays
arrayOfStrings .MyStrings
bool .MyBool
... // etc
```
or perhaps something more verbose:
```C++
#declare .MyVar as ArrayOfStruct
```
This first one would be easier to implement, and is a little less verbose...

What do you think?

**Comment by poppolopoppo** [comment] 2015-08-25 06:49
Explicitly typing variables makes this snippet feel weird :
````javascript
bool .MyBool = true
.MyBool = "hey, I'm a string now"
````
Should not BFF report an invalid assignment error in this case ?

A constructor syntax using function-like grammar is less confusing :
````javascript
.MyBool = bool{ false }
.MyInt = int{ 42 }
.MyString = string{ "bikini" }
.MyArrayOfStrings = ArrayOfStrings{}
.MyArrayOfStrings = ArrayOfStrings{ "a", "b", "c" }
.MyArrayOfStructs = ArrayOfStructs{}
````
But 'ArrayOfStrings' or 'ArrayOfStructs' are parts of internal lexicon and have no sense for the user.

I think that ideally Fastbuild should downcast empty arrays automatically when appending to them for the first time :
````javascript
.array = {} // empty array
.array + 'string' // downcast to array of strings
.array + .struct // invalid assignment
````
````javascript
.struct = []
.array = {} // empty array
.array + .struct // downcast to array of structs
.array + 'string' // invalid assignment
````
Other solutions are putting an unfair burden on the user, and this respects the principle of least astonishment.

Again, I think that **b)** is the best solution. 
It might be easily implemented with this simple change :
````cpp
bool BFFVariable::IsArrayOfStrings() const 
{
     return ( m_Type == BFFVariable::VAR_ARRAY_OF_STRINGS ) || 
            ( m_Type == BFFVariable::VAR_EMPTY_ARRAY ); 
}

bool BFFVariable::IsArrayOfStructs() const 
{
     return ( m_Type == BFFVariable::VAR_ARRAY_OF_STRUCTS ) || 
            ( m_Type == BFFVariable::VAR_EMPTY_ARRAY ); 
}
````

**Comment by poppolopoppo** [comment] 2015-08-26 21:54
I had an epiphany while testing an implementation for this.
I read that code many times, even changed it, but I never realized the true behavior behind BFFParser::StoreVariableToVariable().

---

This :
````javascript
.Boolean = true
.Boolean = 42
Print( .Boolean )
````
````
.Boolean = 42
````
But :
````javascript
.Integer = 42
.Boolean = true
.Boolean = .Integer
Print( .Boolean )
````
````
c:\Test.bff(3,12): FASTBuild Error #1034 - Operation not supported: 'Bool' = 'Int'.
.Boolean = .Integer
           ^
           \--here
````

---

And also his :
````javascript
.ArrayOfStrings = {}
.ArrayOfStrings = 'test'
Print( .ArrayOfStrings )
````
````
.ArrayOfStrings = 'test'
````
But :
````javascript
.ArrayOfStrings = {}
.String = 'test'
.ArrayOfStrings = .String 
Print( .ArrayOfStrings )
````
````
.ArrayOfStrings = // ArrayOfStrings, size: 1
{
    'test'
}
````
Which has the same behavior than :
````javascript
.ArrayOfStrings = {}
.StringToConcat = 'test'
.ArrayOfStrings + .StringToConcat
Print( .ArrayOfStrings )
````
````
.ArrayOfStrings = // ArrayOfStrings, size: 1
{
    'test'
}
````

---

Can you confirm that it was the intended behavior ? I re-read the documentation but could not find more info about this.

**Comment by poppolopoppo** [comment] 2015-08-27 01:17
I found another problem, I post it here because the problem is somewhat related to the dynamic typing implementation described above.

The following BFF example will trigger an assert in debug :
````javascript
.foo = 'FOO'
.foo = { 'bar' }
````
````
Registered <string> variable '.foo' with value 'FOO'

-------- ASSERTION FAILED --------
c:\fastbuild\Code\Core/Containers/Array.h(484): Assert: m_Resizeable == true
-----^^^ ASSERTION FAILED ^^^-----

Registered <ArrayOfStrings> variable '.foo' with 1 elements
````
This happens because .foo is first added to the stack with the string constructor of BFFVariable, which initializes m_ArrayValues as non resizable. All constructors assumes that the variable will not change its type, but this is wrong due to BFFStackFrame [recycling variables](https://github.com/fastbuild/fastbuild/blob/master/Code/Tools/FBuild/FBuildCore/BFF/BFFStackFrame.cpp#L71).

**Comment by ffulin** [comment] 2015-08-28 03:19
The intent is that once you declare a variable to be of a given type, that its type cannot be changed.  That's why the assert fires, because we should never get into that state.

I can confirm that it's not working correctly, either because I didn't do it properly in the first place, or it was broken at some point.

This is correctly reported as an error:
```C++
.Var = 7
.Var = .SomePreviouslyDefinedString // Error #1034 - Operation not supported: 'Int' = 'String'.
```
as is this:
```C++
.Var = 7
{
    .Var = .SomePreviouslyDefinedString // Error #1034 - Operation not supported: 'Int' = 'String'.
}
```

This is currently broken:
```C++
.Var = 7
.Var = 'hello' // Does not fail but should be error 1034 as above
```
as is this:
```C++
.Var = 7
{
    .Var = 'hello' // Does not fail but should be error 1034 as above
}
```
I can fix these, but I'm not sure how big a change it will be, or if it will conflict with your changes for ^.

Speaking of the new operator, it should also cause an error if the type doesn't match:
```C++
.Var = 7
{
    ^Var = 'hello' // Should be error 1034 also
```

**Comment by poppolopoppo** [comment] 2015-08-28 10:42
Ok, thanks for your explanations.

I guess this should be fixed and documented, but I still find this surprising :
````javascript
.array = {}
.string = 'test'
.array + .string
Print( .array ) // { 'test' }
````
````javascript
.array = {}
.string = 'test'
.array = .string
Print( .array ) // { 'test' }  no error 1034, same behavior than concatenation
````

Fixing those will surely conflict with the changes for ^, but not as much as you think.
^ has still the exact same behavior than . and the main change was to explicitly provide the frame where the results will be stored. Every failed type promotion that raises with . will be the same for ^.

In fact, this is already an error :
````javascript
.Var = 7
{
    ^Var = 'hello' // error 1034
````

**Comment by ffulin** [comment] 2015-08-28 15:32
This should also be an error:
```C++
.array = {}
.string = 'test'
.array = .string // should be error 1034 because type would change
.array = "sting" // should be error 1034 because type would change
```
This is ok, since appending String to ArrayOfStrings is allowed:
```C++
.array = {} // array of strings
.string = 'test'
.array + .string // ok
.array + "string" // ok
```

**Comment by kylawl** [comment] 2015-11-16 00:00
Now with the ^ operator we do run into the issue where something like the below fails but is a perfectly valid case.

```
; fbuild.bff
.GlobalArrayOfStructs = {}

#include "Foo.bff"
#include "Bar.bff"

; Foo.bff
{
	.LocalStruct			= [ Name = 'my_struct' Value = 'foo bar' ]
	^GlobalArrayOfStructs	+ .LocalStruct
}

; Bar.bff
{
	.LocalStruct			= [ Name = 'my_struct_again' Value = 'bar' ]
	^GlobalArrayOfStructs	+ .LocalStruct
}
```

In this situation, we must know that Foo came first and declare .GlobalArrayOfStructs in it rather than concat.

**Comment by ffulin** [comment] 2015-11-16 00:08
You are declaring your .GlobalArrayOfStructs as an ArrayOfStrings instead of an ArrayOfStructs

There is currently no way to directly declare an *empty* ArrayOfStructs, but you can do it indirectly as follows:
```C++
.EmptyStruct = []
.GlobalArrayOfStructs = { .EmptyStruct }
```

Naturally that's pretty lame. This issue is tracking the fact that we ideally need a syntax to allow us to  do that more directly.

**Comment by kovarex** [comment] 2016-01-22 10:48
I also encountered this limitation when I tried to combine build type and Architecture type dynamically.
**b)** looks best imho, but I have no idea about the internal changes required.

**Comment by poppolopoppo** [comment] 2016-03-19 15:01
I did not comment here but a month ago I implemented type promotion between an empty array (still considered as an array of strings) to an empty array of structs and concatenation of a struct to an empty of strings.

This is working well and is transparent for the user, and the patch is small :)

**Comment by ffulin** [comment] 2016-07-05 18:03
A change has been integrated that resolves this issue: https://github.com/fastbuild/fastbuild/pull/110

This will be in the next release (v0.91)

**Comment by kovarex** [comment] 2016-08-09 10:22
What does the InTesting Mean? Will it be included in the next version?

**Comment by ffulin** [comment] 2016-08-10 04:29
Hello.  In general, In Testing means a change or fix has been either a) Integrated into the GitHub "dev" branch, or b) implemented in the Perforce mainline.  It generally (but not always) means that the change will be available in the next version (for a particularly risky change, it might stay In Testing for longer). I usually comment on an issue to note when the change/fix can be expected.

For this particular issue, the fix will be in the next version (v0.91).

**Comment by kovarex** [comment] 2016-08-12 13:00
Thank you for the info.

**Comment by ffulin** [comment] 2016-08-26 15:45
v0.91 has been released which includes this change.  Thanks again for your contribution!

**Closed by ffulin** 2016-08-26 15:45 UTC
Labels: Enhancement, In Testing
