### ISSUE TITLE
missing main in object file!

### ISSUE THREAD

**Issue by Domain** [fastbuild/fastbuild#888] opened 2022-01-25 03:18 UTC
While using fastbuild in linux, it may report missing main randomly in some project. I am very confused. I use objdump to see what happen:

builder@188:/export/opm/trunk/20220125/opm_server$ objdump -t obj/servers/payserver/x64/Profile/main.o
obj/servers/payserver/x64/Profile/main.o:     file format elf64-x86-64
SYMBOL TABLE:
0000000000000000 l    df *ABS*  0000000000000000 main.cpp.ii
0000000000000000 l    d  .text  0000000000000000 .text
0000000000000000 l    d  .data  0000000000000000 .data
0000000000000000 l    d  .bss   0000000000000000 .bss
0000000000000000 l     F .text  0000000000000014 _sub_I_00099_0
0000000000000000 l    d  .init_array.00099      0000000000000000 .init_array.00099
0000000000000000 l    d  .debug_line    0000000000000000 .debug_line
0000000000000000 l    d  .debug_str     0000000000000000 .debug_str
0000000000000000 l    d  .note.GNU-stack        0000000000000000 .note.GNU-stack
0000000000000000 l    d  .note.gnu.property     0000000000000000 .note.gnu.property
0000000000000000 l    d  .eh_frame      0000000000000000 .eh_frame
0000000000000000 l    d  .comment       0000000000000000 .comment
0000000000000000         *UND*  0000000000000000 _GLOBAL_OFFSET_TABLE_
0000000000000000         *UND*  0000000000000000 __asan_init
0000000000000000         *UND*  0000000000000000 __asan_version_mismatch_check_v8

builder@188:/export/opm/trunk/20220125/opm_server$ objdump -t obj/servers/payserver/x64/Release/main.o
obj/servers/payserver/x64/Release/main.o:     file format elf64-x86-64
SYMBOL TABLE:
0000000000000000 l    df *ABS*  0000000000000000 main.cpp
0000000000000000 l    d  .text  0000000000000000 .text
0000000000000000 l    d  .data  0000000000000000 .data
0000000000000000 l    d  .bss   0000000000000000 .bss
0000000000000000 l    d  .debug_info    0000000000000000 .debug_info
0000000000000000 l    d  .debug_abbrev  0000000000000000 .debug_abbrev
0000000000000000 l    d  .debug_loc     0000000000000000 .debug_loc
0000000000000000 l    d  .debug_aranges 0000000000000000 .debug_aranges
0000000000000000 l    d  .debug_line    0000000000000000 .debug_line
0000000000000000 l    d  .debug_str     0000000000000000 .debug_str
0000000000000000 l    d  .note.GNU-stack        0000000000000000 .note.GNU-stack
0000000000000000 l    d  .note.gnu.property     0000000000000000 .note.gnu.property
0000000000000000 l    d  .eh_frame      0000000000000000 .eh_frame
0000000000000000 l    d  .comment       0000000000000000 .comment
0000000000000000 g     F .text  000000000000000f main
0000000000000000         *UND*  0000000000000000 _GLOBAL_OFFSET_TABLE_
0000000000000000         *UND*  0000000000000000 _Z11StartServeriPPc

Compare to the Release version, the Profile version has no main symbol! I delete Profile/main.o, and build again, it shows:

builder@188:/export/opm/trunk/20220125/opm_server$ objdump -t obj/servers/payserver/x64/Profile/main.o
obj/servers/payserver/x64/Profile/main.o:     file format elf64-x86-64
SYMBOL TABLE:
0000000000000000 l    df *ABS*  0000000000000000 main.cpp
0000000000000000 l    d  .text  0000000000000000 .text
0000000000000000 l    d  .data  0000000000000000 .data
0000000000000000 l    d  .bss   0000000000000000 .bss
000000000000000f l     F .text  0000000000000014 _sub_I_00099_0
0000000000000000 l    d  .init_array.00099      0000000000000000 .init_array.00099
0000000000000000 l    d  .debug_info    0000000000000000 .debug_info
0000000000000000 l    d  .debug_abbrev  0000000000000000 .debug_abbrev
0000000000000000 l    d  .debug_loc     0000000000000000 .debug_loc
0000000000000000 l    d  .debug_aranges 0000000000000000 .debug_aranges
0000000000000000 l    d  .debug_line    0000000000000000 .debug_line
0000000000000000 l    d  .debug_str     0000000000000000 .debug_str
0000000000000000 l    d  .note.GNU-stack        0000000000000000 .note.GNU-stack
0000000000000000 l    d  .note.gnu.property     0000000000000000 .note.gnu.property
0000000000000000 l    d  .eh_frame      0000000000000000 .eh_frame
0000000000000000 l    d  .comment       0000000000000000 .comment
0000000000000000 g     F .text  000000000000000f main
0000000000000000         *UND*  0000000000000000 _GLOBAL_OFFSET_TABLE_
0000000000000000         *UND*  0000000000000000 _Z11StartServeriPPc
0000000000000000         *UND*  0000000000000000 __asan_init
0000000000000000         *UND*  0000000000000000 __asan_version_mismatch_check_v8

All work fine now. I use distributed compilation with caching enabled.

**Comment by ffulin** [comment] 2022-04-02 00:13
I'm not sure what the problem is, but one thing that stands out is the "main.cpp" vs "main.cpp.ii" section. It's unclear to me why that section name would change between different compilations. It's also not clear why you'd have a problem in one build config and not another.

I have to assume something about your build configuration is different between your configs that is causing this problem or somehow causes a bug to trigger.

Are you able to narrow this down into an isolated repro case you can provide?

**Comment by Domain** [comment] 2022-04-18 02:55
This happen again after 3 months! It's hard to narrow this down. But every time this happen, the filename must be main.cpp.ii. I can delete main.o and build again, all work fine.

**Comment by ffulin** [comment] 2022-04-23 03:07
One avenue to investigate might be distributed vs non-distributed compilation. You can use options like -forceremote to ensure a particular file is built remotely (if it can be). i.e. modify this one source file and compile with and without -forceremote to see if there is a difference in behavior.

**Comment by ffulin** [comment] 2022-08-13 09:46
I'm fairly sure I have fixed the cause of this problem here: https://github.com/fastbuild/fastbuild/commit/9181f5c0fcb0f5d52fa9f57b43ec85989ce461c2

There was a bug where the compiler preprocessed output could be truncated on Linux or OSX in some cases. This bug was far more likely to occur for very small files. If your "main.cpp" was relatively small this would certainly explain why it seemed to occur mostly or exclusively with that file.

Depending on compiler and compiler settings, this could result in a compile error or an empty object.

v1.07 has been released which contains this bug fix. If you haven't already, I recommend updating to that version.

I will close this bug as fixed as I'm pretty sure this is the cause but we can re-open should it turn out to be a different issue.

**Closed by ffulin** 2022-08-13 09:46 UTC
Labels: Question, Need More Info (or Blocked)
