### ISSUE TITLE
UE4.27.2 with Fastbuild compile UnrealHeaderTool error 4294967295 (0xffffffff) 

### ISSUE THREAD

**Issue by astron10** [fastbuild/fastbuild#876] opened 2021-12-21 05:17 UTC
fastbuild version: 1.05
Unreal version: 4.27.2

When compiling UHT, it showed errors:
1>14>PROBLEM: D:\UE427\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\Core\Module.Core.2_of_16.cpp.obj
1>EXEC : error : Unable to create child process
1>EXEC : 16>Failed to build Object. error : 4294967295 (0xffffffff) Target: 'D:\UE427\Engine\Intermediate\Build\Win64\UnrealHeaderTool\Development\CoreUObject\Module.CoreUObject.1_of_9.cpp.obj'

[https://gist.github.com/astron10/4598401a91d064d46f50ac76eb215496](url)

**Comment by ffulin** [comment] 2021-12-21 06:24
This means whatever the UHT is invoking is returning -1 and reporting "Unable to create child process". You'll need to consult the documentation for that tool (or your Unreal integration provider) to understand what might be the cause of that.

**Comment by astron10** [comment] 2021-12-21 13:19
Thanks. Need to change fastbuild source code to fix unreal engine. Solved it!

**Comment by ffulin** [comment] 2021-12-21 23:55
**> Need to change fastbuild source code to fix unreal engine.** 

Do you have any details you can/would like to share? Info about how you resolved this might be useful for someone else if you are able to disclose it.

**Comment by astron10** [comment] 2021-12-26 13:47
https://github.com/razor950/fastbuild-ue4.26.2
This fastbuild branch can be use in 4.27.2, but shaders that used remote compilation do not work well.

**Comment by ffulin** [comment] 2022-01-06 10:15
it sounds like you resolved this issue, so I'm going to close it. Please let me know if you need any more info.

**Closed by ffulin** 2022-01-06 10:15 UTC
Labels: Question
