### ISSUE TITLE
.Dest of Copy has to end with '/' to copy into directory

### ISSUE THREAD

**Issue by Leandros** [fastbuild/fastbuild#213] opened 2017-02-15 23:41 UTC
`Copy` only copies one or multiple files over into a directory if the `.Dest` property ends with a path separator (`/` or `\`).
This could be simplified, and handled similar to what `cp` does on *nix systems.

**Comment by ffulin** [comment] 2017-03-17 03:24
Currently, having a slash on the destination is used to differentiate the case of wanting to rename a single file during copy versus copying that file into a directory.

In terms of cp behaviour, what sort did you have in mind that you feel could be applied to Copy()?

**Comment by Leandros** [comment] 2017-03-20 12:40
`cp` on *nix detects these cases and applies the wanted behaviour appropriately. 

For example:

```
cp /path/to/file.txt /path/to/dir
```

can have multiple behaviours:

- copy `file.txt` into the directory `dir`, if `dir` exists and is a directory
- copy `file.txt` to `dir`, if `dir` is a exists and is a file (`dir` will be overriden)
- copy `file.txt` to `dir` if `dir` does not exist

**Comment by ffulin** [comment] 2017-03-23 03:11
Thanks for the clarification. The concern I have about trying to automatically decide on the correct behaviour, is that it could cause some odd failures caused by race conditions.

Take the following example:
```C++
Copy( 'CopyA' )
{
    .Source  = 'File.1'
    .Dest      = 'Folder/Folder' // note the missing slash
}
Copy( 'CopyB' )
{
    .Source  = 'File.2'
    .Dest      = 'Folder/Folder/'
}
```
Assuming the copy steps have no interdependency, they can be executed in an arbitrary order. The resulting behaviour now depends on which copy occurs first, which could easily result in a copy that works most of the time by luck, until one day it stops working due to unrelated timing changes.

Additionally, a clean build (if you delete the directories) now has a higher chance of not working compared to an incremental build (where folders already exist).

With both those things in mind, I think being more explicit (and chosing the behaviour based on the trailing slash) is favorable: you'll always get the same result regardless of order and/or clean/incremental build.

**Comment by Leandros** [comment] 2017-03-23 08:52
I haven't thought about this. You're absolutely right. 
I would suggest documenting the behavior with the slash, since it might come as a surprise to some users.

**Comment by ffulin** [comment] 2017-09-30 17:18
The documentation for Copy does call out the difference between .Dest being a path or a single file (it might be that the docs were updated since this issue was raised?). Additionally, I've added a new error to catch the common mistake of missing the trailing slash when there are multiple .Source files (https://github.com/fastbuild/fastbuild/commit/72e2bec3aa89c00a5770d6d69fdb98b36621f6aa)

With that in mind, I think we can close this issue. Feel free to re-open (or raise a new issue) if you think there could be further improvements.

**Closed by ffulin** 2017-09-30 17:18 UTC
Labels: Question
