### ISSUE TITLE
Performance of -cacheread and possible optimization opportunities for high end systems

### ISSUE THREAD

**Issue by missmah** [fastbuild/fastbuild#339] opened 2017-11-27 06:31 UTC
`-cacheread` is not effectively using all CPU cores and is also dramatically under-utilizing disk IO, at least on my high-end system.

1. CPU Usage on my 72-thread computer is about 30-50% during a unity `-cacheread -clean` build which I managed to compose of all cache hits.
2. Disk Write Queue rarely reached and far more rarely exceeded `1 concurrent IO`. Modern `NVme SSDs` perform best at queue depths `>= 32` concurrent IOs.
3. Disk Write Speed was hovering around `10-250MB/sec`, on a drive capable of `2100MB/sec`. This is about a factor of 10x-100x slower than the drive's capability.

I don't have proposals about how to fix this yet, but it seems clear that there is fruit hanging somewhere which could improve `-cacheread` build times significantly.

1. Potentially 50-70% CPU under-utilization on high-thread-count machines. Launch more work? Better scheduling? Too much contention for locks in the cache code?
2. It appears that fastbuild is only issuing one IO at a time, sequentially. Uncached overlapped IO tends to be the fastest, at least on `Win32 API`, IIRC. There might be some opportunities to queue up a lot more work before checking for completion. If `32+` simultaneous file writes could be in-progress simultaneously, SSD throughput would probably go through the roof.
3. This one is really a factor of fixing the points mentioned in #2, and also ensuring that writes are large enough and aligned. Large enough is really up to people using e.g. Unity builds to create fewer larger object files. In theory, IO should be the bottleneck here, especially on a system with many unused hardware threads, so it really could be the case that 10x-100x performance gains are possible.

For my build here, `10x` would be an `8.3` second build! And `100x` would be a `< 1` second build!

**Comment by missmah** [comment] 2017-11-27 06:54
One more, related, thought... It should be possible to skip the object file copy in certain cases (e.g. repeated builds, where the object files have not changed since the last time they were read from the cache).

There are three *really good reasons* to investigate this option:
1. Power Savings
2. Build times should be even faster without the writes
3. SSDs have limited write endurance before they die, and preserving it saves money

The idea would be something like this:
1. `Object Cache` continues to compute hashes of prepossessed code and compare those hashes to the cache entries for that file.
2. If there's a hit in the `Object Cache`, check the new `Output Cache` to see whether this copy has already been made before.
  a. If this object file copy has already happened, elide the current copy. Optionally ensure that the destination file still exists and matches the expected timestamp/size in a "safe mode." Skip this check in "fast mode."
  b. If this object file copy has not already happened, perform the copy.
  c. In safe mode, if the object has been moved or changed since the last copy, replace the object again.

I know there are lots of teams who would prefer safe mode, but personally, I would prefer fast mode most of the time. My philosophy is that in the rare occasion that I'm going to go manually mucking with my object files, I can turn safe mode on temporarily.

**Comment by ffulin** [comment] 2017-11-28 03:35
FASTBuild's cache access is multi-threaded - each of the worker threads (one per CPU core) independently performs preprocessing and cache lookups. The cache access is not serialized because as you note, modern systems with SSDs greatly benefit from queued/concurrent IO.  There is no reason there could not be 72 pending IO requests on your machine from the cache lookup perspective.  However, if there are other bottlenecks causing reduced CPU usage, then certainly reduced IO throughput is likely to be a side-effect of that. I think focusing on the apparent CPU inefficiency is the way to go here.

FASTBuild doesn't have any contention highly contentious locking issues between threads that I've seen in any profiling I've been doing, but your "high-end" system (somewhat of an understatement :) ) could certainly be uncovering bottlenecks that just don't show up on regular-human 8 or 12 core PCs :)

The walking of the dependency database to queue jobs for the workers is single threaded (and needs to be). I've not seen this be the bottleneck, but again it's entirely possible on your machine it is.

Outside of FASTBuild itself, it's possible your build has additional dependencies or your bff is structured in a way that doesn't cause too much inefficiency in a "real" build but shows up when using the cache due to vastly reduced timing of individual tasks.

In any case, I think to get the bottom of this, we'd need to profile your build. Since you are running your own built executables, you just need to build them in Profile build configuration. After a run, there will be a profile.json file in the working dir which you can view in chrome's about::tracing window. That should immediately tell us if the (lack of) CPU usage is thread idle time or idle time due to contention.  From there, you can add more profile sections to drill into interesting bits.

**Comment by ffulin** [comment] 2017-11-28 03:37
I'm a little confused by your second comment. FASTBuild only copies object files from the cache when the inputs to the object file have changed or you are forcing a clean build.  With that in mind, optimizing out the copy of a thing we need to build doesn't make sense - we shouldn't be building it in the first place if nothing has truly changed.

Perhaps I've misunderstood what you mean?

**Comment by ffulin** [comment] 2017-12-03 17:50
Are you running custom exe built form the "dev" branch? I just fixed a dev-branch regression (https://github.com/fastbuild/fastbuild/commit/e373fdc11266f2d069eb46bbddbe422e13a1d032) which was causing linking to be serialized on the main thread.

I don't think that necessarily explains what you are seeing, but it certainly won't be helping!

**Comment by ffulin** [comment] 2017-12-03 18:09
Also - are you running Windows 10 (or server equivalent)?  I think this case will be particularly impacted by the Windows 10 process destruction bug that you mentioned in https://github.com/fastbuild/fastbuild/issues/264 because the more cache hits you have, the more shor-lived the processes are.

**Comment by ffulin** [comment] 2018-04-29 00:11
@missmah  - I'm going to close this old issue for now. Please let me know if there is anything outstanding you want to address: we can re-open or create a new issue as needed.

**Closed by ffulin** 2018-04-29 00:11 UTC
Labels: Need More Info (or Blocked), Question
