### ISSUE TITLE
Caching fails on objects with certain naming formats

### ISSUE THREAD

**Issue by ClxS** [fastbuild/fastbuild#67] opened 2015-10-22 10:35 UTC
Caching fails on objects which follow a name.cpp.obj format. This makes caching incompatible with things such as Unreal Engine 4 which uses this format.

The responsible bit of code is ObjectNode.cpp:389:
```cpp
// use preprocesed output path as input
Node * sourceFile = GetSourceFile();
fullArgs.Replace( sourceFile->GetName().Get(), tmpFileName.Get() );
```
This ends up replacing the output file name as well, which causes the object to just get created in my temp directory, leading to the build eventually failing when it can't find the object.

My dirty not-so-nice solution was to look for a character (' ' or '"') at the end of the source file name.
```cpp
//Replace Instances followed by space
{
	AString safeFileName;
	safeFileName = GetSourceFile()->GetName();
	safeFileName += " ";
	AString safeTempName;
	safeTempName = tmpFileName;
	safeTempName += " ";
	fullArgs.Replace(safeFileName.Get(), safeTempName.Get());
}
//Replace Instances followed by "
{
	AString safeFileName;
	safeFileName = GetSourceFile()->GetName();
	safeFileName += "\"";
	AString safeTempName;
	safeTempName = tmpFileName;
	safeTempName += "\"";
	fullArgs.Replace(safeFileName.Get(), safeTempName.Get());
}		
```
There's definitely better ways, this was just the fastest fix.

**Comment by ffulin** [comment] 2015-10-27 02:10
Indeed the problem is that both the source cpp file and the destination object get replaces, when only the source object should.

Your work-around seems safe (for your use-case). I'll look into creating a more robust fix.

Unless you absolutely need the object files to end in .cpp.obj, you could also look at modifying the output extension to just .obj?

Thanks for reporting this bug!

**Comment by ClxS** [comment] 2015-10-27 08:53
Yeah ideally I would've just changed all the objects to follow what you'd expect (just .obj), but with Unreal it'd mean changing the UnrealBuildTool a little deeper in than we probably should. But yeah, with my quick-fix I'm happy to say it works perfectly with Unreal! :)

**Comment by ffulin** [comment] 2015-11-15 18:43
I've submitted a fix for this issue to the Perforce mainline. It will be part of the next release (v0.88)

I've reworked the way command line args are managed. As part of that re-work I've changed how the input filename swapping is handled. It's now part of the argument construction instead of a post-construction fixup, which means it works reliably and won't "fixup" the wrong thing.

**Comment by oliviergaertner** [comment] 2015-12-01 15:47
Hi CIxS,

Does this mean that there is way of using fastbuild with unreal engine? This is something I've been looking at (small indi studio here :) )

If it's the case can we get in touch to talk about it?

**Comment by ClxS** [comment] 2015-12-02 09:05
Yeah it's possible. It took us about a week to get it working properly since we had to fix a few issues first.
You need to make changes to the UnrealBuildTool. You can use how SNDBS works as a base, and rather than constructing the .bat, construct the .bff.

There's a few things we had to do to get it working perfectly. We have to read the ActionCommand, extract the exe being called, as well as the input/output. This bit is the most difficult part of the whole thing really.
Once you've got a list of all objects/actions, since you're just passed the libraries to build for already compiled objects, I used a DLL node for all linking nodes. This triggers a bug in FASTBuild where it reports a DLL node using lib.exe as a EXE_NODE, stopping it being used as a dependency for other DLLs. I've got a temporary fix for that in one of my branches (Fix_DllLibNodeFix)
Other things to note, since the DLL node doesn't (yet) support non-link dependencies I've had to separate it into two passes: an object compilation pass, and a linking pass. Adding the dependency option so I can do it in one pass is on my to-do list.

We've only tested it working on Win64 for now, but yeah it was surprisingly easy to get working.

**Comment by oliviergaertner** [comment] 2015-12-02 09:33
Awesome!

I'll have a look at all this :) Do you mind if I ask you a few question when I'll have a look at all this?

**Comment by ClxS** [comment] 2015-12-02 10:11
Sure, feel free!
Just drop a comment on one of my commits if you've got a question, so we don't end up spamming this issue. :)

**Comment by ffulin** [comment] 2015-12-10 05:56
v0.88 has now been release and includes a fix for this issue.

**Closed by ffulin** 2015-12-10 05:56 UTC
Labels: bug, In Testing
