### ISSUE TITLE
Control of linking groups (for --whole-archive etc)

### ISSUE THREAD

**Issue by AlinaPVoicu** [fastbuild/fastbuild#787] opened 2020-10-08 07:55 UTC
Hi,

Opening a separate issue with our question.

We're currently mainly using fastbuild to build android. Because on Android the linking order is important and because we sometimes have JNI code in some of the dependencies (so we need to guard the dependency having JNI with "-Wl, --whole-archive" in the linking command), we switched to using .PreBuildDependencies instead of .Libraries which would also add the deps to the linking order without allowing us to properly use linking flags when needed.

Everything works fine except for what ffulin mentioned in a separate issue: "A changed dependency will NOT cause a re-link". Because of this, when there's a change in the dependencies list, the changes don't reach the final binary which is a big problem.
We're currently trying to see if we can adjust fastbuild to take into consideration the changes happening in the PreBuildDeps list as well, in the meantime we figured it might be a good idea to check in with you as well and see how we should be using the fastbuild api properly.

What is your advice for us? 
If we were to use .Libraries, we'd have some of the dependencies twice in the linking command forcing us to use "-Wl, --allow-multiple-definition" - which is actually what we've done so far, but we wanted to switch away from it since we don't think it's ok to use that flag as a default since it might hide real issues.

So far for us the best solution would be that .PreBuildDeps triggers re-linking when necessary.
Is there a reason why this isn't the default behavior?

Thank you!

**Comment by ffulin** [comment] 2020-10-10 15:56
### About PreBuildDependencies

.PreBuildDependencies exists to allow ordering of tasks who's *result* you depend on, without the task itself being a dependency.

The most common example of this is code generation. If you have a custom tool that generates source code, you have the compilation of that source code set .PreBuildDependencies on that code generator. This ensures your code generator is run before any downstream building of the generated code. When your code generator runs (either always or based on some changed input) it might modify only a subset of your files (or even none). If .PreBuildDependencies triggered downstream builds in this case, every time your code generator ran, it would force a clean build. Instead, having the dependencies on the output of the generator means the downstream building only occurs if the generated code changes as expected.

Additionally, FASTBuild uses .PreBuildDependencies internally for things like directory listing operation scheduling.

So .PreBuildDependencies are working as intended and should not be changed. If you locally modify them for your use-case, it's very likely to cause problems, either now or in the future.

### Workarounds

FASTBuild respects the order the .Libraries are specified when expanding the %1 input, but doesn't provide a mechanism currently for seperate "groups" or for injecting args between sets of inputs. There are several work-arounds for this, including some you mentioned. Here are some additional options to consider in the short term:

**1. Wrap everything in -whole-archive**

Depending on your needs, you may be able to wrap the entire %1 injection with -whole-archive. Naturally this may have linking implications you need to consider.

**2. Manually specify external dependencies**

FASTBuild supports specifying dependencies directly on the command line (instead of via %1) for things that are discovered via library paths (i.e. pre-built external libraries). If the things you need to wrap in -whole-archive are existing prebuilt libraries, you might be able to specify those manualy while still listing your own libraries via .Libraries and using %1.

### Proper Fix

Not being able to control the link order well is a shortcoming of FASTBuild that would ideally be fixed.

I think a new property is required, that would allow you to specify groups of Libraries and then control how they are injected into the command line. I can think of two ways we might handle this:

**1. .LinkerLibraryGroups with Pre and Post commands**

We could allow multiple groups to be specified and expanded into %1.
```
.Group1 = [
            .PreCommand = '--whole-archive'
            .Libraries = { ... } // Your libs in here
          ]
.Group2 = [
            .PreCommand = '--no-whole-archive'
            .Libraries = { ... } // Your libs in here
          ]
.LinkerLibraryGroups = { .Group1, .Group2 }
```
FASTBuild would then expand all of those into %1, in order

**2. .LinkerLibraryGroups with Multiple injections**

We could allow multiple groups to be specified and the allow control of how they are injected into the LinkerOptions. The exact syntax would need to be decided, but the pseudo-config would be as follows:
```
.Group1 = { ... } // Your libs in here
.Group2 = { ... } // Your libs in here
.LinkerLibraryGroups = { .Group1, .Group2 }
.LinkerOptions = "--whole-archive %1A --no-whole-archive %1B'
```
I'd probably lean towards this second option as it assumes the least about the linker command line, avoids moving some linker options out of the command line, and feels like it'd be more flexible in general.

It might even be possible to make .Libraries simply work this way (rather than adding a new option) while maintaining backwards compatibility (i.e. expands all to %1, or each group to %1A etc)

**Comment by ffulin** [comment] 2020-10-10 16:08
I've renamed this issue to reflect the core problem we need a solution for.

**Comment by AlinaPVoicu** [comment] 2020-10-12 11:08
Hi ffulin,

Thank you for the quick analysis and answer!
We'll try to refrain then from modifying the behavior of  .PreBuildDependencies.

Regarding the proposed **workarounds**:
1. **Wrap everything in -whole-archive-** 
This isn't a great solution since it'll keep the linker from removing the unused code, hence increasing the final size of the binary. Not a bad solution, but we'd still avoid it.

2. **Manually specify external dependencies**
Technically all dependencies are pre-built, but through fastbuild as well, so unless we call the dependency's alias with fastbuild or fastbuild itself knows to build it, we won't have it pre-built. 
It's similar to what we want, just that fastbuild won't be in charge of building the dependencies that have JNI.
Honestly rather than doing this it would be faster to just delete the .so each time we build - most of the time link time isn't that costly in the end. Not a great fix though either.

Regarding the **Proper fixes**:
1. **.LinkerLibraryGroups with Pre and Post commands**
Wouldn't it be a bit more intuitive for your example to be written like this?
`.Group1 = [
            .PreCommand = ' -Wl,--whole-archive'
            .Libraries = { ... } // Your libs in here
            .PostCommand = ' -Wl,--no-whole-archive'
          ]
.Group2 = [
            .Libraries = { ... } // Your libs in here
          ]
.LinkerLibraryGroups = { .Group1, .Group2 }`
Also...how would this work with the "-Wl,--start-group"/"-Wl,--end-group" flags? Guarding the whole linking list with the two flags lets us avoid having to have the proper linking order in place, so we should be able to use them as well. This would mean we'd need to be able to have Groups contain other groups as well if I understand your example correctly.
If that would be ok I wouldn't have a problem with this solution.

2. **.LinkerLibraryGroups with Multiple injections**
The second option sounds a bit more intuitive, indeed, though it would be a bit more prone to mistakes in the way that you'd need to be careful to properly match the group with its parameter.

Both solutions are ok, slightly inclining towards the second one as well.

Would you have time to include this enhancement in the next Fastbuild release?
If so, do you guys have an ETA for the next release?

Thank you for your time!

**Comment by AlinaPVoicu** [comment] 2020-10-23 11:52
Hi @ffulin ,

Bumping the thread.
We'd prefer to not mess with the dependencies system too often so so far we've been waiting for an ETA for the change.
If you know you can't fit this change any time soon please let me know.

Thank you and let me know if there's any other info I can help with!

**Comment by ffulin** [comment] 2020-10-26 02:40
There is no specific ETA for the next release, but one is likely to occur in the next few weeks.

In terms of implementing this specific feature, I'm still mulling over the implementation. As it will be adding a new type of syntax (the %1 modifications) I want to be sure it makes sense in the long term and is maintainable. I will try to get this into the next release.

**Comment by AlinaPVoicu** [comment] 2020-10-26 08:16
Thanks ffulin!
Let me know if there's anything we can help with in the process.

**Comment by ffulin** [comment] 2020-12-07 03:28
I wasn't able to implement this feature exactly as I had hoped, as it requires some non-trivial plumbing to expose Arrays of Arrays of strings to the bff files (as per the "second option" discussed above).

To avoid delaying this feature any further, I've implemented an partial solution in https://github.com/fastbuild/fastbuild/commit/f59dc9d5174ae978999d8848941f533552d7e138.

With this change, DLL and Executable expose a new .Libraries2 parameter which can be used to specify a second set of libraries. Using %1 will now inject both .Libraries and .Libraries2.

An extension to the %1 syntax however, allows the command to specify each group independently using %1[0] and %1[1] as follows:
```.LinkerOptions = '-Wl,--whole-archive %1[0] -Wl,--no-whole-archive %1[1]'```

In the future, I will hopefully remove .Libraries2, allowing .Libraries to use an Array of Arrays syntax that I mentioned befoe. The syntax for %1 in .LinkerOptions can then be extended to an arbitrary number of groups indexing with [].

Hopefully this will solve this issue enough for your use-case.

This change will be in the next release (v1.03). I'll leave this issue open until that version is released.

**Comment by ffulin** [comment] 2020-12-14 02:38
v1.03 has now been released and contains this new functionality.

Let me know if that doesn't resolve for your use-case and we can discuss followup changes if needed.

**Closed by ffulin** 2020-12-14 02:38 UTC
Labels: Enhancement, Resolved In Next Version

**Comment by akito05** [comment] 2020-12-28 10:10
Hello,

We saw file `LinkerNode.cpp` has code
![image](https://user-images.githubusercontent.com/29190316/103206847-6911d900-492f-11eb-9f61-1b2ee811bbb5.png)
Is it correct or should we change it to check `foundB` ?

**Comment by ffulin** [comment] 2021-01-06 06:16
@Yuki-Nguyet Thankyou - this is indeed a bug.

I've applied a fix (https://github.com/fastbuild/fastbuild/commit/fdf5a182a8a41912639e97004efb940dc55c7753) which will be in the next release (v1.04)
