### ISSUE TITLE
Occasionally compile error occurs on Mac

### ISSUE THREAD

**Issue by rhetty** [fastbuild/fastbuild#929] opened 2022-09-08 08:57 UTC
FBuild sometimes fails to compile cpp files because of syntax error. It happens when the file is compiled on remote machine.
![image](https://user-images.githubusercontent.com/11970875/189073825-02c698c3-98bf-411b-a630-0b712d95cfb9.png)
The code in error info is different from the source:
![image](https://user-images.githubusercontent.com/11970875/189074045-73495b5a-6fdf-4a4a-b58e-2997eac369e7.png)
"2" turns into "<U+0012>" for some reason.
Is the problem already known or fixed?
The fbuild version is v1.05

**Comment by ffulin** [comment] 2022-09-11 02:15
I've never seen this issue before, but I can think of two possible avenues to investigate:

*a) a corrupt network stream.*

In FASTBuild versions prior to v1.07 there was a bug that could result in corrupt network streams. It seems unlikely that this would corrupt the stream in such a precise and (presumably) repeatable way, but it would make sense to eliminate this as a cause first.

Are you able to update your fbuild and fbuildworker processes to v1.07? This should be a simple upgrade as there should be no breaking changes or deprecations since v1.05.

*b) a problem with Clang's preprocessor, possibly related to charsets or file encoding*

(I'm assuming you are using Clang since that's usually the case on Mac)

Is this problem reliably reproducible if you use -forceremote to ensure the file is always built remotely? If not, does it only happen on certain machines? Are you using any special charsets or file encodings?

**Comment by rhetty** [comment] 2022-09-13 03:54
We are trying to reproduce this problem for more information...

**Comment by ffulin** [comment] 2022-11-26 05:27
Were you able to upgrade to a newer version to see if the issue was related to some bugs that have been fixed? And if not fixed, did you have any success with narrowing down a repro case?

**Comment by rhetty** [comment] 2023-01-12 10:53
When we did not use fbuild, it happened again.
So... we guess it is Mac's problem. There may be an error of the memory or disk.

**Comment by ffulin** [comment] 2023-01-13 21:40
Thanks for letting me know. Since this seems to be a problem unrelated to FASTBuild, I'll close the issue.

**Closed by ffulin** 2023-01-13 21:40 UTC
Labels: Question, Need More Info (or Blocked)
