### ISSUE TITLE
Compilation errors are output in standard out stream

### ISSUE THREAD

**Issue by Jairard** [fastbuild/fastbuild#255] opened 2017-06-06 08:35 UTC
I am currently trying to print compilation errors to a file, but when i try to redirect the error stream of the fastbuild executable with the command `./fbuild -config fbuild.bff Target -summary 2> err.log`, the file remains empty.
Of course, when I redirect the standard output to a file with `./fbuild -config fbuild.bff Target -summary 1> out.log`, the resulting file contains both fastbuild output and compilation errors.

When redirecting the streams directly in the compiler command generated by fastbuild, it works as expected (i.e. the error are output in the error stream). That's why I suspect that the problem comes from fastbuild, maybe it catches both out and error streams and outputs them in the same stream.

I can probably modify the fastbuild script to use stream redirection in the compilation command, but I thought that it could be nice to fix this issue.

**Comment by ffulin** [comment] 2017-06-11 17:30
FASTBuild does indeed route everything through stdout. This is by design, and I chose to do that for a couple of reasons:
*1) Dealing with other tools.*  FASTBuild invokes many other compilers, linkers etc and they all have differing behaviors when it comes to stdout vs stderr. Additionally, they often change how they behave depending on what command line options are pased. I wanted to standardize the output of FASTBuild to abstract this issue away.
*2) Ordering.* Having everything routed through one place makes it much easier to see the related messaging, which is particularly important in a multi-threaded environment. Routing some things through stdout and some through stderr loses all context in terms of the relationship between those bits of info.

It would certainly be possible to modify the output of FASTBuild to keep the streams isolated, but given that everything has been written with a unified mindset, this would require a significant amount of rework to several systems.

The output of FASTBuild has been designed to be primarily human readable. If you are looking at routing errors to a file in order to more easily parse them, perhaps an approach that could work would be to use the output generated by the -monitor command line option. This optional outputs a machine-readable file including error information. (The option is undocumented as it has been in beta, but I recently resolved the last known issue with it so I plan to promote it to fully supported in v0.94).

Do you think that might be a way to solve for your use-case?

**Comment by Jairard** [comment] 2017-09-07 07:38
Thanks for your anwser, and sorry for the delay of mine.
Actually I wanted to get stderr output to fetch include-what-you-use recommendations, but I worked around the problem by generating the compilation database, and then feeding it to include-what-you-use.

**Comment by ffulin** [comment] 2017-10-07 19:45
If you have no objection, I'll close this issue as resolved.

**Comment by Jairard** [comment] 2017-10-13 15:39
Sure, go ahead.

**Closed** 2017-10-14 00:37 UTC
Labels: Question
